cds-snc/forms-terraform

forms/aws/ecs.tf, forms/aws/task-definitions/form_viewer.json, forms/aws/variables.auto.tfvars, forms/aws/variables.tf
This PR adds the env vars for SSC forms template ID and submission email address.
=> Change and add env vars for Forms

.github/workflows/terraform.yml, forms/aws/ecs.tf, forms/aws/task-definitions/form_viewer.json, forms/aws/variables.tf
Remove env variables from the terraform config.  They will be included directly with the app instead.
=> Remove vars and upgrade tf workflow

forms/aws/lambda.tf, forms/aws/lambda/templates/templates.js, forms/aws/networking.tf
Just a hello world for now.
Updated to give lambda permission to access the new RDS
=> Scaffold out a lambda for template processing

forms/aws/ecs.tf, forms/aws/lambda.tf, forms/aws/lambda/templates/templates.js, forms/aws/secrets.tf, forms/aws/task-definitions/form_viewer.json
There's a few other minor TF changes needed for the lambda.
templates.js is still WIP but putting it up anyways - will probably have another iteration in a future PR.
I asked a question in slack about the secretArn that the client is looking for - for now I've just guessed that we need to make a terraform secret with the DB password, but I wouldn't be surprised if that's entirely incorrect.
Repost of the question for context:
> One of the things the aws client-rds-data wants passed in to a db request is a “secretArn” which is described as “The name or ARN of the secret that enables access to the DB cluster.” I am having difficulty understanding what this means...
=> More tf changes and basic lambda code

forms/aws/lambda/reliability/lib/dataLayer.js, forms/aws/lambda/reliability/lib/notifyProcessing.js, forms/aws/lambda/reliability/reliability.js, forms/aws/lambda/submission/submission.js
This PR refactors some of the logic out of the reliability lambda and into supporting libs in order to prepare for the addition of the vault storage
=> Storage vault

forms/aws/lambda/templates/templates.js
I'm making this PR so that the code I am testing in the AWS console can be followed along with here, as I build it out in conjunction with the forms app side.
Current state:
Can INSERT JSON into the DB, and can GET it back out and return the result
=> Template Lambda code updates

.github/workflows/sandbox.yml, .github/workflows/terraform.yml, forms/aws/lambda.tf, forms/aws/lambda/reliability/lib/notifyProcessing.js, forms/aws/lambda/reliability/nodejs/package.json, forms/aws/lambda/reliability/nodejs/yarn.lock
This PR gets the Notify Processing path to fetch the form template from the Templates Lambda.
It also bumps the security scan action to version 2.2.3
=> Add form config to notify processing

.github/workflows/sandbox.yml, .github/workflows/terraform.yml, bootstrap/provider.tf, bootstrap/variables.auto.tfvars, forms/aws/cloudwatch.tf, forms/aws/dynamo.tf, forms/aws/ecr.tf, forms/aws/ecs.tf, forms/aws/lambda.tf, forms/aws/lambda/notify_slack/notify_slack.js, forms/aws/lambda/reliability/lib/dataLayer.js, forms/aws/lambda/reliability/lib/markdown.js, forms/aws/lambda/reliability/lib/notifyProcessing.js, forms/aws/lambda/reliability/lib/vaultProcessing.js, forms/aws/lambda/reliability/nodejs/package.json, forms/aws/lambda/reliability/nodejs/yarn.lock, forms/aws/lambda/reliability/reliability.js, forms/aws/lambda/retrieval/nodejs/package.json, forms/aws/lambda/retrieval/retrieval.js, forms/aws/lambda/submission/submission.js, forms/aws/lambda/templates/templates.js, forms/aws/networking.tf, forms/aws/provider.tf, forms/aws/rds.tf, forms/aws/redis.tf, forms/aws/s3.tf, forms/aws/secrets.tf, forms/aws/task-definitions/form_viewer.json, forms/aws/variables.auto.tfvars, forms/aws/waf.tf
This PR implements the following new features and enhancements:
- Vault: Storage of form submissions. (New Dynamo DB Table and Lambda function) 
- Template API: CRUD operations that remove template dependence on files included in the app repository and instead move the templates to a DB.  (New PostgreSQL Aurora instance and Lambda function)
- Ensure reliability queue handles errored submissions properly and submits to the Dead Letter Queue.
- Fix alarm on new entries into the Dead Letter Queue
=> Merge Sandbox Prototyping Infrastructure (Vault, Template Uploads, etc.) into Main

README.md, forms/aws/lambda/install_package.sh, forms/aws/lambda/local_development/template.yml, forms/aws/lambda/templates/nodejs/package.json, forms/aws/lambda/templates/nodejs/yarn.lock, forms/aws/lambda/templates/templates.js
Templates lambda running locally against local Postgres DB (formsDB DB name)
=> Local RDS Lambdas / AWS support

.github/workflows/terraform.yml, bootstrap/provider.tf, forms/aws/lambda.tf, forms/aws/lambda/load_testing/lambda_locust.py, forms/aws/lambda/load_testing/locust_test_file.py, forms/aws/s3.tf
This PR creates a new Lambda function that runs a Locust test file against staging.
This Lambda will be invoked through the AWS CLI and not directly from the application.
=> Load testing lambda

forms/aws/lambda/organisations/organisations.js
=> select from correct table

forms/aws/ecs.tf, forms/aws/lambda.tf, forms/aws/lambda/reliability/lib/dataLayer.js, forms/aws/lambda/reliability/lib/notifyProcessing.js, forms/aws/lambda/reliability/lib/s3FileInput.js, forms/aws/lambda/reliability/lib/vaultProcessing.js, forms/aws/lambda/reliability/reliability.js
closes https://github.com/cds-snc/platform-forms-client/issues/355
=> Document upload

forms/aws/lambda/reliability/lib/s3FileInput.js
=> use then instead of async await

forms/aws/lambda/reliability/lib/s3FileInput.js
=> Add catch to response of s3 call for copy files

.github/workflows/terragrunt-apply-scratch.yml, .github/workflows/terragrunt-plan-scratch.yml, aws/network/inputs.tf, aws/network/network.tf, aws/network/outputs.tf, aws/network/security_groups.tf, aws/network/vpc_endpoints.tf, aws/network/vpc_flow_log.tf, env/scratch/network/.terraform.lock.hcl, env/scratch/network/terragrunt.hcl
Creates the VPC, subnets, security groups, endpoints and
flow logs for the Forms network.
Original module code in:
* e3e5be5
* 5c8f647 
* #28
=> feat: Terragrunt network module

.github/workflows/terragrunt-apply-scratch.yml, .github/workflows/terragrunt-plan-scratch.yml, aws/.checkov.yml, aws/redis/inputs.tf, aws/redis/outputs.tf, aws/redis/redis.tf, env/scratch/redis/.terraform.lock.hcl, env/scratch/redis/terragrunt.hcl
Creates the ElastiCache Redis replication group used by the Forms app.
Original module code in:
5c8f647
* #28 
=> feat: Terragrunt Redis module

.github/workflows/terragrunt-apply-scratch.yml, .github/workflows/terragrunt-plan-scratch.yml, aws/.checkov.yml, aws/rds/inputs.tf, aws/rds/rds.tf, env/common/provider.tf, env/scratch/rds/.terraform.lock.hcl, env/scratch/rds/terragrunt.hcl
Creates the RDS PostgreSQL cluster used by Forms.
Original module code:
5c8f647
* #28 
=> feat: Terragrunt RDS PostgreSQL cluster

.github/workflows/terraform.yml, forms/aws/lambda/reliability/lib/dataLayer.js, forms/aws/lambda/reliability/lib/markdown.js, forms/aws/lambda/reliability/lib/notifyProcessing.js, forms/aws/lambda/reliability/reliability.js, forms/aws/lambda/submission/submission.js
Part 2/2 to close https://github.com/cds-snc/platform-forms-client/issues/336 
- Set the language of the submission in the DynamoDB record using a key named `FormSubmissionLanguage` 
- Use this key in the notifyProcessing to set the subject and question title in the language chosen 
- Fix mixed async/await and promise code styles in various places
Will need to merge and test in staging for this one 
N/A
Please complete the following items in the checklist before you request a review:
=> feat: i18n Notify email

.github/workflows/terragrunt-apply-scratch.yml, .github/workflows/terragrunt-plan-scratch.yml, aws/load_balancer/certificates.tf, aws/load_balancer/inputs.tf, aws/load_balancer/kinesis.tf, aws/load_balancer/lb.tf, aws/load_balancer/outputs.tf, aws/load_balancer/route53.tf, aws/load_balancer/waf.tf, env/scratch/load_balancer/.terraform.lock.hcl, env/scratch/load_balancer/terragrunt.hcl
Add the load balancer, certificates, WAF ACL and Kinesis logging.
Original module code:
* 7afba07
* 16995ce
* 0541ca4 
* e570b35
* #28 
=> feat: Terragrunt load balancer

.github/workflows/terragrunt-apply-scratch.yml, .github/workflows/terragrunt-plan-scratch.yml, aws/app/ecs.tf, aws/app/ecs_iam.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf, aws/app/lambda.tf, aws/app/lambda_iam.tf, aws/app/secrets.tf
Makes the infrastructure changes required by the JWT bearer
token to the app module.
* #117
=> chore: sync bearer token infra changes to app module

aws/app/ecs_iam.tf
closes https://github.com/cds-snc/platform-forms-client/issues/495
This PR adds an IAM policy to allow ECS to read and write the DyanoDB database
N/A
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la performance?
risque d’utiliser des dépendances ajoutées?
setup, etc.) | …
=> feat: Modify ECS IAM to give access to DynamoDB

aws/app/ecs_iam.tf
Add missing KMS policy on ECS instance
=> Dynamodb policy

aws/app/ecs_iam.tf
Includes PartiQL commands from ECS/Forms to DynamoDB.
=> Dynamodb policy update to include PartiQL

aws/app/ecs_iam.tf
Allow the lambda function to access the indexes on the vault table
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> …
=> fix: Allow access to vault indexes by lambda

README.md, aws/app/lambda/archive_form_responses/archiver.js, aws/app/lambda/invoke_archiver.sh, aws/app/lambda/invoke_reliability.sh, aws/app/lambda/local_development/template.yml, aws/app/lambda/reliability/lib/dataLayer.js, aws/app/lambda/reliability/lib/s3FileInput.js, aws/app/lambda/reliability/reliability.js, aws/app/lambda/submission/submission.js, aws/dynamodb/dynamo.tf, env/common/local-provider.tf, env/local/app/.terraform.lock.hcl, env/local/app/terragrunt.hcl, env/local/dynamodb/.terraform.lock.hcl, env/local/dynamodb/terragrunt.hcl, env/local/env_vars.hcl, env/local/kms/.terraform.lock.hcl, env/local/kms/terragrunt.hcl, env/local/sns/.terraform.lock.hcl, env/local/sns/terragrunt.hcl, env/local/sqs/.terraform.lock.hcl, env/local/sqs/terragrunt.hcl, env/terragrunt.hcl
There is not task for this. The summary of the problem however is we have not been able to run forms fully locally until now ! By using localstack to simulate AWS services locally we are now able to fully run all lambdas locally and have them behave very similarly to what we can expect on AWS
https://user-images.githubusercontent.com/26819992/150104573-a250058d-8582-4da9-969e-b073ed2d6134.mov
Please see the update README in this PR to be able to test this
=> feat: enable local development of lambdas using localstack !

aws/app/lambda/reliability/lib/dataLayer.js, aws/app/lambda/reliability/reliability.js
* fixed regression with reliability 
N/A
=> fix: error with retrieval of DynamoDB SubmissionTimestamp

aws/app/lambda/submission/submission.js
- Found a small bug while trying to debug something in Staging
- Fixed serialization issue when adding item to DynamoDB
=> fix: submit issue in staging

aws/app/ecs_task/form_viewer.json
Renamed ReCAPTCHA public site env variable
=> Rename env var for reCaptcha

aws/app/lambda/reliability/lib/dataLayer.js, aws/app/lambda/reliability/lib/vaultProcessing.js, aws/app/lambda/reliability/reliability.js, aws/app/lambda/submission/submission.js
[card](https://github.com/cds-snc/platform-forms-client/issues/701)
[deps](https://github.com/cds-snc/platform-forms-client/pull/728)
=> add security attribute to forms

aws/app/ecs_task/form_viewer.json
Ensure common spelling of Recaptcha throughout the project
=> fix secret spelling of Recaptcha

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-staging.yml, aws/app/ecs.tf, aws/app/ecs_iam.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf, aws/cognito/outputs.tf, aws/cognito/secrets.tf, aws/cognito/user_pool.tf, env/local/app/terragrunt.hcl, env/staging/app/terragrunt.hcl, env/staging/cognito/.terraform.lock.hcl, env/staging/cognito/terragrunt.hcl
Adds a simple cogntio instance to the AWS infrastructure and ensures the ECS application has the required information for Next-Auth
=> Add cognito module to staging

aws/load_balancer/lb.tf, env/common/common_variables.tf, env/terragrunt.hcl
Enable load balancer access logging and send those logs to the Cloud Based Sensor satellite bucket.
* #173
=> feat: enable load balancer accessing log to CBS bucket

aws/cognito/user_pool.tf
No issue.
Summary of changes done: 
* enable user self signup
* enable verification of email
* set email attribute as email
=> feat: Setup cognito for server side auth

aws/cognito/user_pool.tf
* remove client secret from app client
* set email verification to be with code
=> fix: Remove client secret from app client

aws/app/ecs.tf, aws/app/ecs_iam.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf, env/staging/app/terragrunt.hcl
Removes the linking of the non-existant secret to the ECS Applictation
=> Remove all referecned of cogntio_client_secret

aws/app/ecs_iam.tf, aws/app/inputs.tf, aws/cognito/outputs.tf, env/staging/app/terragrunt.hcl
IAM permissions for Forms client ECS
=> feat: add iam permissions to forms client ECS

aws/app/lambda/reliability/lib/templates.js
- Fixed issue with `map` function while archiving form templates
=> fix: issue with map function while archiving form templates

aws/app/lambda/dead_letter_queue_consumer/nodejs/package.json
- Fixed DLQ consumer lambda missing a dependency
=> fix: DLQ consumer lambda is missing a dependency

aws/app/lambda/dead_letter_queue_consumer/dead_letter_queue_consumer.js
- Fixed DLQ lambda function unable to parse message body
=> fix: DLQ lambda unable to parse message body

aws/app/lambda/dead_letter_queue_consumer/dead_letter_queue_consumer.js
- Fixed wrong formatting in message body generated by DLQ lambda
=> fix: wrong message body formatting

aws/load_balancer/waf.tf
Backport of #294 from Main to Develop
=> Remove logic creating 2 different WAF settings for Prod and Staging 

aws/cognito/user_pool.tf
=> fix: install lambda dependencies for cognito

aws/cognito/lambda_iam.tf
fix cognito not being able to invoke lambda
=> fix: use only supported value for version

aws/cognito/user_pool_iam.tf
Fixing missing association between Cognito role and Cloudwatch policy
=> Associate policy to role

.github/workflows/terragrunt-plan-production.yml, aws/cognito/user_pool.tf
cognito domain per environment
=> fix: unique domain per cognito environment

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml, aws/app/ecs.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf
Adds ENV vars for email addresses: contactus and support.
Note: will also update the forms code PR to use contact_us
=> Adds env vars for contactus and support emails

aws/app/lambda/reliability/lib/dataLayer.js, aws/app/lambda/reliability/nodejs/package.json
closes https://github.com/cds-snc/platform-forms-client/issues/1053
- Add `Status` and `ConfirmationCode` fields when saving submission to the Vault
=> feat: add Status and ConfirmationCode fields when saving submission to the Vault

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml
Updates support email. (See slack #Forms-Support for more background)
=> Updates support email to a more correct one

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml
Fixes Staging and Production github action variables for the Support address
=> Fix support email address

aws/app/lambda.tf
- Fixed deployment issue with new Nagware lambda
=> fix: deployment issue with Nagware lambda

aws/app/lambda/nagware/nagware.js
=> fix: for loop syntax

aws/app/lambda/audit_logs/audit_logs.js, aws/app/lambda/invoke_audit_logs.sh, aws/sqs/sqs.tf
Fixes the issue where CLI Output in Localstack is different than what the Lambda actually receives as input when in service.
=> CLI output different than Lambda Input

aws/app/lambda/nagware/lib/postgreSQLDataLayer.js
- Nagware inner function did not receive expected argument.
=> fix: nagware function argument is not defined

README.md
=> fixing spelling on README.md

aws/cognito/user_pool.tf
- Added missing permissions between Cognito and Lambdas
=> fix: missing permissions between Cognito and Lambdas

aws/cognito/lambda.tf, aws/cognito/lambda/cognito_email_sender/cognito_email_sender.js, aws/cognito/lambda/pre_sign_up/pre_sign_up.js, aws/cognito/user_pool.tf
(pull request is against new `feature/2fa_authentication` branch)
- Added account auto confirmation using pre sign up lambda
=> feat: added account auto comfirmation using pre sign up lambda

aws/cognito/lambda.tf, aws/cognito/lambda/cognito_email_sender/cognito_email_sender.js, aws/cognito/lambda/pre_sign_up/pre_sign_up.js, aws/cognito/user_pool.tf
=> Feature/2FA Authentication through Email

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/scripts/terraform_apply_localstack.sh, env/local/app/.terraform.lock.hcl, env/local/dynamodb/.terraform.lock.hcl, env/local/kms/.terraform.lock.hcl, env/local/sns/.terraform.lock.hcl, env/local/sqs/.terraform.lock.hcl
Update the devcontainer configuration so that it
can create the local infrastructure.
=> fix: local devcontainer setup

aws/pr_review/security_groups.tf
Fixes a typo from #397 
Previous PR tf apply failed on merge due to this typo
=> Fix redis port mapping

aws/pr_review/iam.tf
Adds Parameter Store access permission to Lambda Client role.
=> Add iam policy to grant parameter store access to lambda client role

aws/alarms/cloudwatch.tf
- Added missing Cloudwatch subscription filter for submission logs
=> feat: added missing cloudwatch subscription filter for submission logs

aws/alarms/lambda/notify_slack/notify_slack.js, aws/app/lambda/audit_logs/audit_logs.js, aws/app/lambda/dead_letter_queue_consumer/dead_letter_queue_consumer.js, aws/app/lambda/nagware/lib/emailNotification.js, aws/app/lambda/nagware/lib/postgreSQLDataLayer.js, aws/app/lambda/nagware/nagware.js, aws/app/lambda/reliability/lib/dataLayer.js, aws/app/lambda/reliability/lib/notifyProcessing.js, aws/app/lambda/reliability/lib/s3FileInput.js, aws/app/lambda/reliability/lib/templates.js, aws/app/lambda/reliability/reliability.js, aws/app/lambda/submission/submission.js, aws/cognito/lambda/cognito_email_sender/cognito_email_sender.js
- Format all console logs (log, warn, error) in JSON
=> chore: format all console logs in JSON

aws/alarms/lambda/notify_slack/notify_slack.js
- Fixed multiple issues in the NotifySlack lambda
=> fix: multiple issues with NotifySlack lambda

aws/load_balancer/waf.tf
This PR ams to reinstate  staging  terraform state.
=> disabled waf regex till provider is merged

README.md
Updates the readme to inform devs about the need to sign commits when opening a PR
=> doc: update readme to inform about signed commits on this repo

aws/app/lambda/nagware/lib/templates.js, aws/app/lambda/nagware/nagware.js
closes https://github.com/cds-snc/platform-forms-client/issues/2477
- Reworked Nagware warning message being sent to Slack
=> refactor: rework Nagware warning message being sent to Slack

aws/app/lambda/nagware/nagware.js
- Fixed Nagware notification layout
=> fix: nagware notification layout

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml
Update the Notify Slack workflow step to include
the target Slack channel.
- https://github.com/cds-snc/platform-core-services/issues/441
=> fix: set target Slack channel for notification

aws/load_balancer/waf.tf
Updates waf to allow /forms path vs /myforms path
See: https://github.com/cds-snc/platform-forms-client/pull/2683
=> Fix allowed path

aws/load_balancer/waf.tf
- Allow path to verification files for search engines tool
=> chore: allow path to verification files for search engines tool

aws/load_balancer/cloudfront.tf, aws/load_balancer/s3.tf
- Fix for maintenance mode deployment issue on AWS
=> fix: maintenance mode deployment issue

aws/load_balancer/certificates.tf, aws/load_balancer/route53.tf, aws/load_balancer/waf.tf
- Revert some of the changes on the certificate including ELB DNS
=> fix: revert certificate changes including ELB DNS

aws/load_balancer/cloudfront.tf, aws/load_balancer/s3.tf
- Added missing aliases in Cloudfront distribution
=> fix: missing aliases in Cloudfront distribution

README.md
Fixes several typos in `README.md`
=> [docs] Updates README.md

aws/load_balancer/waf.tf
- Fixed maintenance mode WAF rules to allow for new resources to be loaded in the HTML page
=> fix: maintenance mode WAF rules to allow for new page resources to be loaded

aws/lambdas/code/nagware/lib/dynamodbDataLayer.ts, aws/lambdas/code/nagware/lib/templates.ts, aws/lambdas/code/nagware/package.json
- Fixed pg package import in Nagware lambda
- Use pg version 8.7.3 to be consistent with the other lambdas
=> fix: import pg package was not properly done in Nagware lambda

aws/cognito/lambda_iam.tf
Duplicate iam policy name detected.
=> fix: duplicate policy name

aws/.checkov.yml, aws/app/ecs.tf
Pin ECS version to 1.4.0 and ignore checkov rule.
=> Pin version of ecs platform

aws/alarms/cloudwatch.tf
closes https://github.com/cds-snc/forms-terraform/issues/579
- Add a new Cloudwatch subscription filter on all Lambda log groups to detect function timing out in order to send a Slack notification
=> feat: send notification on Slack when a timeout is detected in the lambda logs

.github/CODEOWNERS
Add Clement to approved releasers
=> Allow Clement to approve releases

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-all-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml, aws/file_scanning/vault_scan_object.tf, env/cloud/file_scanning/terragrunt.hcl
linked to https://github.com/cds-snc/scan-files/pull/872
- Enable file scanning on Vault S3 bucket
=> feat: enable file scanning on Vault S3 bucket

.env.example, docker-compose.yml
Add localstack pro env variable for license token and uses persistance.
=> chore: Add Localstack Pro

aws/lambdas/code/reliability/lib/dataLayer.ts, aws/lambdas/code/reliability/lib/markdown.ts, aws/lambdas/code/reliability/lib/types.ts
See issue https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3377
=> Add the new combobox (aka searchable list) for email responses

aws/app/ecs_task/form_viewer.json
Following this control advice
https://docs.aws.amazon.com/securityhub/latest/userguide/ecs-controls.html#ecs-5
=> fix: Container gets read-only access to its root file system.

lambda-code/audit-logs-archiver/package.json, lambda-code/audit-logs/package.json, lambda-code/cognito-email-sender/package.json, lambda-code/cognito-pre-sign-up/package.json, lambda-code/form-archiver/package.json, lambda-code/load-testing/Dockerfile, lambda-code/nagware/package.json, lambda-code/notify-slack/package.json, lambda-code/reliability-dlq-consumer/package.json, lambda-code/reliability/package.json, lambda-code/response-archiver/package.json, lambda-code/submission/package.json, lambda-code/vault-integrity/package.json
- Force trigger deployment of Lambda container images
=> chore: added description in all package.json files

.github/lambda-filter.yml, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, aws/ecr/ecr.tf, aws/ecr/outputs.tf, aws/load_testing/inputs.tf, aws/load_testing/lambda.tf, env/cloud/load_testing/terragrunt.hcl, lambda-code/force-deploy-images.txt
- Fixes a few issues we have with the deployment of containerized Lambda functions
=> chore: wait for lambdas images to be ready to use before applying Terraform modules

.github/workflows/terragrunt-apply-production.yml
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
=> fix: production deployment issue

.github/workflows/terragrunt-apply-production.yml
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
=> fix: deployment issue in production

lambda-code/submission/main.ts
- Adds more information to the error message we get when failing to save a submission
=> chore: add more information to the error message we get when failing to save a submission

aws/alarms/dashboards/forms_service_health.tmpl.json
- Connects new healthchecks logs from web app in GC Forms healtcheck dashboard
=> feat: connects new healthchecks logs from web app in GC Forms healtcheck dashboard

aws/alarms/dashboards/forms_service_health.tmpl.json
- Fixes broken layout for Health check Cloudwatch dashboard
=> fix: healthchecks dashboard layout is broken

aws/alarms/dashboards/forms_service_health.tmpl.json
Update the service health dashboard with new sections for Form responses and user sign in.
=> feat: add health dashboard sections

.github/production-lambda-functions.conf, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml
- Solidify lambda functions matrix definition using a configuration file where we list functions that need to be deployed in production
Note: while implementing the changes I tested it using the plan staging workflow to make sure it was working.
=> chore: solidify lambda functions matrix definition using a configuration file where we list functions that need to be deployed in production

aws/alarms/cloudwatch.tf, aws/alarms/inputs.tf, aws/lambdas/outputs.tf, env/cloud/alarms/terragrunt.hcl
Add CloudWatch alarms for the following three functions:
1. `form-archiver`: expect 1 invocation per day.
2. `nagware`: expect 1 invocation on Tuesday, Thursday and Sunday.
3. `response-archiver`: expect 1 invocation per day
=> feat: add CloudWatch Lambda function invocation alarms

aws/app/ecs.tf, aws/app/locals.tf
Update Staging so that it is also running multiple Form viewer tasks.
=> fix: scale Staging to multiple ECS tasks

aws/alarms/athena.tf, aws/alarms/inputs.tf, aws/network/outputs.tf, aws/network/security_groups_connector.tf, env/cloud/alarms/terragrunt.hcl
Creates a dedicated security group for the RDS connector rather than using the RDS SG
=> fix: create dedicated security group for connector

aws/idp/waf.tf
Update the casing of the excluded common rule from the IdP WAF. Also add a comment explaining why it is being excluded.
- https://github.com/cds-snc/platform-forms-client/issues/3938
- #759
=> fix: name of IdP excluded common rule

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-all-staging.yml, .github/workflows/terragrunt-plan-staging.yml, aws/app/ecs.tf, aws/app/ecs_iam.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf, aws/secrets/inputs.tf, aws/secrets/outputs.tf, aws/secrets/secrets.tf, env/cloud/app/terragrunt.hcl, env/cloud/secrets/terragrunt.hcl
We need a master admin service account to manage the machine service account keys. This is related to [this Forms App pull request](https://github.com/cds-snc/platform-forms-client/pull/4147).
=> feat: add new secrets for Zitadel

aws/idp/route53.tf
Update to use the ESDC security email for IdP DMARC reports.
=> chore: update IdP DMARC security email

lambda-code/cognito-email-sender/main.ts
- Fixes broken import in Cognito Email Sender lambda function
=> fix: wrong import in Cognito Email Sender lambda function

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-all-staging.yml, .github/workflows/terragrunt-plan-staging.yml, aws/app/ecs.tf, aws/app/ecs_task/form_viewer.json, aws/app/inputs.tf, aws/secrets/inputs.tf, aws/secrets/outputs.tf, aws/secrets/secrets.tf, env/cloud/app/terragrunt.hcl, env/cloud/secrets/terragrunt.hcl
Initial setup for Sentry API key.
=> chore: Sentry API key setup

aws/api/ecs.tf, aws/api/inputs.tf, env/cloud/api/terragrunt.hcl
- Adds Freshdesk API key secret to API ECS task
=> feat: add Freshdesk API key secret to API ECS task

aws/api/ecs.tf
- Adds ENVIRONMENT_MODE env var to API ECS task
=> feat: add ENVIRONMENT_MODE env var to API ECS task

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml
Update the Terraform prod plan/apply workflows to deploy and manage the API resources in production.
=> feat: deploy API to prod

.github/workflows/terragrunt-plan-staging.yml
Changes branch to watch for staging terraform plan.
=> fix: Add missing workflow change for staging terraform plan

lambda-code/reliability/lib/dataLayer.ts, lambda-code/reliability/lib/types.ts
Copied from #862
This should allow Emails to process the Address Complete components output.
Fixes : https://github.com/cds-snc/platform-forms-client/issues/4419
=> fix: Add ability to process address complete in emails.

aws/network/security_groups_lambda.tf
Adds missing egress rule from lambda to RDS
=> fix: Add egress rule from lambda to db

lambda-code/reliability/lib/dataLayer.ts, lambda-code/reliability/lib/notifyProcessing.ts
- Fixes issue with undefined answer for dynamic row question type
=> fix: handle undefined answer for dynamic row question type

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-all-staging.yml, .github/workflows/terragrunt-plan-staging.yml, aws/ecr/ecr.tf, aws/ecr/inputs.tf, env/cloud/ecr/terragrunt.hcl
Adds an ECR policy in Staging that allows CDS Organization accounts to pull and use Lambda images.
=> feature: Add cross acount policy for ECR in Staging only

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-all-staging.yml, .github/workflows/terragrunt-plan-staging.yml, aws/ecr/ecr.tf, aws/ecr/inputs.tf, env/cloud/ecr/terragrunt.hcl
Last one before I start click ops'ing
=> feature: ecr policy to allow cross acoutn sharing

aws/ecr/ecr.tf
- Adds new `forms_app_legacy` ECR repository for the Rainbow deployment service
=> feat: forms app legacy ECR

Makefile, aws/ecr/ecr.tf, aws/lambdas/iam.tf, aws/lambdas/inputs.tf, aws/lambdas/nagware.tf, aws/lambdas/prisma_migration.tf, aws/lambdas/reliability.tf, aws/lambdas/vault_integrity.tf, aws/s3/outputs.tf, aws/s3/s3.tf, env/cloud/lambdas/terragrunt.hcl, lambda-code/prisma-migration/Dockerfile, lambda-code/prisma-migration/base_schema.prisma, lambda-code/prisma-migration/bootstrap, lambda-code/prisma-migration/prisma.sh, local_dev_files/build_dev_env.sh
Adds a lambda that can be triggered to read prisma files from an S3 bucket and then run the migration and seed the database.
=> feature: Lambda prisma migration

local_dev_files/build_dev_env.sh, local_dev_files/destroy_dev_env.sh
Adds a run timer to the build and destroy infrastructure actions.
=> chore: add timers to run scripts

aws/pr_review/ecr.tf, aws/pr_review/iam.tf, aws/pr_review/inputs.tf, aws/pr_review/lambda.tf, aws/pr_review/security_groups.tf
- Destroys PR review environment resources that will be shared with Rainbow deployment feature
=> feat: destroy PR review environment resources that will be shared with Rainbow deployment feature

aws/glue/jobs.tf, aws/glue/scripts/submissions_etl.py
Adds a new flag to the submissions ETL "bath_size" if set to daily will only grab the past 24 hours. Otherwise the whole thing.
=> fix: Add a mode toggle for submissions so it can just be done easy peasy.

aws/glue/jobs.tf, aws/glue/scripts/rds_etl.py, aws/glue/scripts/submissions_etl.py
* Adds cron for submissions.
* Checks if user has Publish perm, and adds true/false to new element : "CanPublish"
* Fixes pagination for submissions. See : https://boto3.amazonaws.com/v1/documentation/api/1.26.93/reference/services/logs/client/filter_log_events.html
=> fix: Submission Cron Job / Pagination & Ability to Publish Status for Users

aws/idp/rds.tf
- Fixes Aurora version mismatch for our IdP RDS cluster
=> fix: aurora postgresql version for IdP RDS cluster

aws/lambdas/cloudwatch.tf
- Increases API end to end test frequency
=> chore: increase API end to end test frequency

aws/network/security_groups_api.tf
- Opens local communication between API and IdP through security groups
=> fix: opens local communication between API and IdP through security groups

lambda-code/load-testing/main.py, lambda-code/load-testing/run_load_test_in_lambdas.py
- Reworks load test lambda payload to comply with Invokust library
=> fix: rework load test lambda payload to comply with Invokust library

idp/docker/config.yaml
- Tweaks Zitadel config to try to fix recurring Zitadel Notifier errors
=> fix: trying to fix recurring Zitadel Notifier errors

lambda-code/reliability/src/lib/dataLayer.ts, lambda-code/reliability/src/lib/notifyProcessing.ts, lambda-code/reliability/src/lib/types.ts, lambda-code/reliability/src/main.ts
fixes https://github.com/cds-snc/platform-forms-client/issues/6095
- Adds support for file attachment for existing forms having file input components
=> fix: handle file attachments with email delivery method
