cds-snc/forms-terraform

forms/aws/cloudwatch.tf

This PR removes the notification in Slack for deployments that have started or are successful in the Staging environment.  Deployment failures still raise alerts through Slack.

Reduce notifications for staging

---

forms/aws/networking.tf

This PR creates a default VPC security group with no ingress of egress rules (block by default).
This fixes [Issue 102 SRE](https://github.com/cds-snc/site-reliability-engineering-internal/issues/102)

Set default security group for vpc

---

forms/aws/ecr.tf
forms/aws/lambda.tf
forms/aws/lambda/reliability/lib/dataLayer.js
forms/aws/lambda/reliability/reliability.js
forms/aws/lambda/submission/submission.js
forms/aws/sqs.tf

This PR modifies the logic around form submission processing at the SQS entry point.
Previous Logic:
Send uuid to sqs -> Get receipt and save with submission data in DB
New Logic:
Save submission to DB -> Send uuid to SQS -> Update submission DB item with sqs receipt
This will prevent race conditions from happening when saving to the DB.  A delay of 5 seconds has also been introduced before the SQS will process the event to aid in mitigating race conditions on saving the sqs receipt to the DB.

Save submission logic

---

forms/aws/lambda/reliability/lib/markdown.js
forms/aws/lambda/reliability/reliability.js

Applying the changes done in the NextJS app to support customizing the email subject line, if provided in the form's JSON config: https://github.com/cds-snc/platform-forms-client/pull/170
Note: Prettier was applied to the files, let's chat if we need to align formatting?

Support custom email subject, if provided in the form JSON config

---

bootstrap/provider.tf
forms/aws/ecr.tf
forms/aws/secrets.tf

This PR ignores the terraform security scan suggestions to use customer managed encryption keys for Secrets Manager, Dynamo DB keeping terraform state, and ECR.
The current settings leverage AWS's default encryption key.  This can be looked at in the future if needed for protected data.

ignore warning about using global encryption key

---

forms/aws/lambda/reliability/reliability.js

Currently we append the word `Submission` to the email subject line. Checked with Stevie-Ray and it's not needed. Updated production separately.

Don't append the word Submission to the subject line

---

forms/aws/lambda/templates/templates.js

This PR fleshes out the basic Templates Lambda:
- GET method now accepts an optional formID value to GET a specific form from the DB instead of all of them
- Added UPDATE and DELETE methods

build out the rest of the Lambda API methods

---

forms/aws/lb.tf

This PR updates the health check to test against `/api/version` instead of `/en`.  This is due to `/en` invoking the Template Lambda for each page render to properly gather published pages.
This PR saves a little $$$.

Change endpoint that is used for health checks

---

bootstrap/provider.tf
forms/aws/ecr.tf
forms/aws/ecs.tf
forms/aws/lambda.tf
forms/aws/rds.tf
forms/aws/redis.tf
forms/aws/s3.tf
forms/aws/secrets.tf
forms/aws/task-definitions/form_viewer.json
forms/aws/vpc_flow_log.tf

This PR creates 3 S3 buckets:
- reliability_file_storage: to store file attachments while form submissions are being processed through the reliability queue.  File will auto delete after 5 days.
- vault_file_storage: to store file attachments after a form has been processed and sent to the vault.
- archive_storage: to store file submissions and file attachments for up to 30 days in case recovery efforts are required.

S3 reliability queue

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

This VS Code devcontainer creates a development environment
for Terraform and Terragrunt work.
* #28 

feat: add Terraform devcontainer

---

forms/aws/ecs.tf
forms/aws/networking.tf

This PR removes the egress rule that allowed outbound traffic from the ECS task to the internet.  This was a remanent from the source projects infrastructure (Covid Portal) that required the rule for outbound information to New Relic.
This current project does not require such access.
Closes #42

Remove egress from ECS to Internet

---

forms/aws/networking.tf

The `forms_egress` security group must be removed in two steps.  This
change will allow it to be removed from the ECS tasks that are still
referencing the SG.
A subsequent PR will then remove the security group.
* #89

fix: ECS egress security group removal

---

forms/aws/ecs.tf

The app needs internet egress to complete the Google Authentication token exchange.
The destruction of `aws_security_group_rule.forms_egress_s3` is from local testing that was preformed last night which was giving the `forms` security group access to the private S3 Gateway.  This would be required if the ECS task did not have internet egress.
* #89
* #92

fix: internet egress required by Google Auth

---

.github/workflows/terraform.yml

This will cause the Terraform plan/apply workflow to only run when the Terraform root module or workflow files have been updated.
The reason for this change is to limit unnecessary Terraform plan/apply runs against the infrastructure as the Terragrunt refactor is performed.
* #28 

fix: limit scope of Terraform GitHub workflow

---

.bootstrap/tfstate.tf
.github/workflows/terragrunt-apply-scratch.yml
.github/workflows/terragrunt-plan-scratch.yml
.gitignore
Makefile
aws/hosted_zone/hosted_zone.tf
env/scratch/hosted_zone/.terraform.lock.hcl
env/scratch/hosted_zone/terragrunt.hcl
env/terragrunt.hcl

This hosted zone holds all DNS records required by the Forms service.
Also included:
* Terragrunt plan and apply GitHub workflows
* Fix to `tfstate.tf` S3 remote state to enable versioning.
* Fix to `.gitignore` to allow Terraform lock files.  This allow us 
to pin provider/module versions for consistent Terraform 
plan and apply commands.
* Makefile with common commands. 
* #28

feat: Terragrunt to create the Route53 hosted zone

---

.github/workflows/terraform-security-scan.yml
.github/workflows/terragrunt-apply-scratch.yml
.github/workflows/terragrunt-plan-scratch.yml
aws/.checkov.yml
aws/kms/kms.tf
aws/kms/outputs.tf
env/scratch/hosted_zone/terragrunt.hcl
env/scratch/kms/.terraform.lock.hcl
env/scratch/kms/terragrunt.hcl

Creates the Customer Managed Keys (CMKs) that are used to
encypt/decrypt CloudWatch and DynamoDB data.  
Also includes Terraform static analysis workflow with checkov.
Ref: original source for module is 014e912cf 
* #28

feat: Terragrunt KMS module

---

.github/workflows/terragrunt-apply-scratch.yml
.github/workflows/terragrunt-plan-scratch.yml
aws/dynamodb/dynamo.tf
aws/dynamodb/inputs.tf
env/scratch/dynamodb/.terraform.lock.hcl
env/scratch/dynamodb/terragrunt.hcl

Creates the reliability queue and vault DynamoDB tables used by Forms.
Original module code:
414146c
* #28 

feat: Terragrunt moodule for DynamDB tables

---

.github/workflows/terragrunt-apply-scratch.yml
.github/workflows/terragrunt-plan-scratch.yml
aws/.checkov.yml
aws/ecr/ecr.tf
aws/ecr/outputs.tf
env/scratch/ecr/.terraform.lock.hcl
env/scratch/ecr/terragrunt.hcl

Creates the ECR that holds the Form viewer Docker images
used by the ECS cluster.
Original module code:
5c8f647
* #28 

feat: Terragrunt Elastic Container Registry

---

aws/app/ecs_iam.tf

The IAM policy resources needs to reference the S3 bucket
ARNs and not their IDs.
* #108

fix: ECS S3 IAM policy

---

aws/alarms/lambda.tf

This policy allows CloudWatch access for the Notify Lambda function and means we don't have to maintain our own policy definition.
* #112

fix: switch to managed AWS Lambda policy

---

.github/workflows/terraform-version-check.yml

This will create a comment on PRs if there is an update available for Terraform or Terragrunt.  It is a non-blocking check meant as a reminder for the team.
The comment looks like so:

feat: workflow to check for Terraform updates

---

aws/app/lambda/templates/templates.js

Sync the fix to the Staging `temlates.js` Lambda to `ExecuteStatementCommand`
which creates a command instead of passing params object templates lambda.

chore: sync templates.js Lambda fix from Staging

---

aws/load_balancer/waf.tf

Allow for dynamic firewall rules depending on the environment:
1. Only block on `PostRequestLimit` exceeded in Production. This
is to support load testing in Staging.
2. Exclude the `CrossSiteScripting_BODY` in Staging.
No plan changes are expected since this is the current WAF ACL setup in Staging.
* #28 

feat: dynamic WAF ACL rules per environment

---

.github/workflows/diff-comment.yml
.github/workflows/version-manifest.yml

Fix diff comment as it does not have access to workflow
environment variables.
Fix version manifest to expose the job outputs and properly
references the previous commit SHA.
These were problems identified testing #128

fix: diff comment and version manifest workflows

---

aws/app/lambda/reliability/lib/dataLayer.js

This PR updates the markdown format sent to the Notify Template.
Questions are now bolded, and responses do not have bullets in front of them unless they are in a list.
Dynamic Rows elements have the row heading placed above each response.

Update email formatting for notify markdown

---

env/production/app/terragrunt.hcl

The source for this module must be local since it requires that the
`aws/app/lambda` dependencies are installed before running
`terraform plan/apply`.  If a remote Terraform module is used,
this step can't happen.
A future fix to this would be using Docker images to create
the Lambda functions so that no dependency install step
is required.
* #128

fix: install Lambda dependencies for prod

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml
env/production/alarms/.terraform.lock.hcl

Now that the Alarms Terraform state has been migrated to the
Terragrunt `alarms` module, it can be managed by the prod
GitHub workflow.
There should be no changes for this PR.  It will be applied during
the subsequent `VERSION` prod release PR.
* #28 

feat: add Alarms module to Production releases

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/alarms/sns.tf
aws/kms/kms.tf
aws/kms/outputs.tf
aws/load_balancer/shield.tf
env/common/provider.tf
env/production/alarms/terragrunt.hcl
env/staging/alarms/terragrunt.hcl

Adds the ALB and Route53 hosted zone to AWS Shield Advanced's
DDoS protection.
Also creates DDoS CloudWatch alarms and the SNS topics,
subscriptions and KMS keys required for the `us-east-1`
hosted zone alarm.
* #130

feat: add DDoS protection to ALB and hosted zone

---

aws/alarms/lambda.tf

Add the Lambda permission required that allows the `us-east-1`
SNS topics to invoke the Slack notify Lambda used by CloudWatch
alarms.
* #150 
* #130

fix: add SNS topic permission to invoke Slack Lambda

---

aws/app/ecs_iam.tf

Attach the dynamodb policy to the ECS forms role.

Attach dynamodb policy to ecs role

---

aws/app/lambda/templates/templates.js

There is no issue for this fix.
**Problem:** This was returning a boolean value for `organization` and `bearerToken` instead of the actual value. It will continue to return `undefined` if the values for `record[2]` or `record[3]` are `null` or `undefined`. 
This only applies when not using the `process.env.AWS_SAM_LOCAL`.

fix: Change return value from boolean to actual value.

---

aws/app/lambda/reliability/lib/notifyProcessing.js

This PR ensures that when an error array object is returned from the Notify API that it is parsed and printed to the logs to ensure the detail of the issue is captured.
Current displayed error does not provide enough detail to identify the issue:
`data: { errors: [Array], status_code: 400 }`

Ensure detail from notify api error is captured and logged

---

aws/app/lambda/templates/templates.js

There is no issue for this fix.
**Problem:** This was returning a JSON object with either:
`{isNull: true}` or 
`{stringValue: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyFoo3JtSUQiOjIzBariaWF0IjoxNjFoOTI3BAR1LCJleHAiOfO0BaR2ODQ3NDV9.DNxKOAReVOLEXy6zA4BU4vCCL9vaEsiJ5ZbAFOOBAR-h8"}`
It was necessary to access the `.stringValue` property of the object, if it existed.
If there was no value, when returning `undefined`, the `bearerToken` was omitted from the results. Returning `null` solved that issue.
This only applies when not using the process.env.AWS_SAM_LOCAL, because of the differences between Aurora Postgres and Postgres used in development in Docker.
This Lambda can only be tested after it's been deployed in the AWS Staging environment, since it needs to connect to the Aurora DB, which is …

fix: Use `stringValue` for Aurora Postgres.

---

aws/dynamodb/outputs.tf

Fix for following error:
`
End User Forms Critical - Form responses archiver: Failed to retrieve consumed form responses. Reason: 1 validation error detected: Value '["retrieved-index"]' at 'indexName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+.
`

fix: archiver lambda index name value is wrong

---

aws/app/outputs.tf

Splitting PR #168 in two because the output and input dependency are causing conflicts.

Add outputs to app module for new alarm

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
env/production/alarms/terragrunt.hcl
env/staging/alarms/terragrunt.hcl

This PR creates an alarm at the warning level when an Error is detected processing form responses in the reliability queue.  This is a first warning sign alarm that should be followed by another warning alarm that a response has been sent to the dead letter queue.

Alarm for error in Reliaiblity Queue processing

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/load_balancer/outputs.tf
aws/load_balancer/waf.tf
env/production/alarms/terragrunt.hcl
env/staging/alarms/terragrunt.hcl

closes https://github.com/cds-snc/platform-forms-client/issues/615
Added alarm to track when a temporary token has been generated from outside of Canada

feat: alarm for tracking temporary token request made from outside of Canada

---

aws/app/lambda/templates/templates.js

Closes #170.
Explicitly specifying the fields to be returned from the query, and explicitly omitting the `bearerToken` field from any GET requests for the templates. This is because that API call is made from both authorized and unauthorized users, and the bearerToken is a secret that should only be viewed by authorized users.

fix: remove `bearerToken` from the return data.

---

aws/alarms/cloudwatch.tf
aws/app/ecs_iam.tf

closes https://github.com/cds-snc/platform-forms-client/issues/617
linked to https://github.com/cds-snc/platform-forms-client/pull/635
- adds log metric filter on ECS log group to catch error when an expired bearer token has been used
- adds alarm to use new expired bearer token metric in order to send Slack warning

feat: add log metric filter on ECS Log group and associated alarm that will tell us when an expired bearer token has been used

---

aws/alarms/cloudwatch.tf

closes https://github.com/cds-snc/platform-forms-client/issues/616
linked to https://github.com/cds-snc/platform-forms-client/pull/636
- adds log metric filter on ECS log group to catch error when we failed to generate a temporary token too many times
- adds alarm to use new "failed to generate a temporary token too many times" metric in order to send Slack warning

feat: add log metric filter on ECS Log group and associated alarm that will tell us when we failed to generate temporary token too many times

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/load_balancer/outputs.tf
env/production/alarms/terragrunt.hcl
env/staging/alarms/terragrunt.hcl

- Fixed TemporaryTokenGeneratedOutsideCanadaWarn alarm not using the right triggering metric

fix: TemporaryTokenGeneratedOutsideCanadaWarn alarm not using the right triggering metric

---

aws/alarms/cloudwatch.tf

API call failure rates (500 http errors)
Closes #618
https://github.com/cds-snc/platform-forms-client/issues/618
This will need to be deployed to **Staging**, and then some 500 errors will need to be triggered to test that the alarm goes off.

feat: alarm 5xx errors

---

aws/app/lambda/submission/submission.js

* Fixed submissionID reference error due to catch block not having access to block scoped submissionID in the try block
* Fixed SubmissionTimestamp value needing to be a string 
N/A

fix: error with DyanamoDB SubmissionTimestamp key

---

aws/app/inputs.tf

Mark the secret app module variables as `sensitive` so that they are not
leaked by the Terraform Plan action comment.

fix: mark secret app variables as sensitive

---

aws/app/lambda/reliability/lib/dataLayer.js
aws/app/lambda/templates/templates.js
env/common/local-provider.tf

Linked to issue https://github.com/cds-snc/platform-forms-client/issues/586
Summary of changes:
* Setting `Retrieval` to have a value of `0` when a record is first being inserted to the vault 
* Fixed a local only bug whereby sql parameters were in the wrong order for updating template record 
* Setting local environment terraform version to be the same as staging and production for consistency 
Please see the following PR https://github.com/cds-snc/platform-forms-client/pull/694

fix: sql parameters in wrong order and addition of retrieved attribute

---

aws/app/lambda.tf
aws/sqs/sqs.tf

closes #33 
closes #192 
This PR enables the redrive policy to allow queues to redrive messages from the DLQ as well as increases the timeout for the reliability lambda to 5 min
See hashicorp documentation on `redrive_allow_policy`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#redrive_allow_policy
See AWS documentation on redrive 
https://aws.amazon.com/blogs/aws/enhanced-dlq-management-sqs/

feat: enable DLQ redrive and increase timeout for reliability lambda

---

aws/sqs/sqs.tf

remove redrive-allow-policy which doesn't work with SQS FIFO queues

fix: remove redrive allow policy

---

aws/app/lambda/reliability/lib/dataLayer.js
aws/app/lambda/reliability/lib/markdown.js
aws/app/lambda/reliability/lib/notifyProcessing.js
aws/app/lambda/reliability/lib/vaultProcessing.js
aws/app/lambda/reliability/reliability.js
aws/app/lambda/submission/submission.js

closes https://github.com/cds-snc/platform-forms-client/issues/687
closes https://github.com/cds-snc/platform-forms-client/issues/595
This PR mainly adds the submission ID and a timestamp to the end of the email body
In french:
In english:
I was not able to find a good way to shorten the UUID unfortunately. Taking the first 8 characters would mean a duplicate every 65000 IDs. Base64 encoding the ID based on its bytes did shorten the ID to 22 characters however it did not make much of a difference when it came to being read by a screenreader and in fact was even more confusing. Unfortunately there is not a really good solution for this other than a user controlling the reading speed of the screen reader. 
Also fixed a couple of issues:
* language attribute not included 
* misspelled …

feat: Add submissionID and createdAt timestamp to email body

---

.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/app/ecs.tf
aws/app/ecs_task/form_viewer.json
aws/app/inputs.tf
aws/app/lambda.tf
aws/app/lambda/local_development/template.yml
aws/app/lambda/reliability/lib/notifyProcessing.js

This PR aims to enable the support of notify's Callback function  per GC forms environment. 
[Card](https://github.com/cds-snc/platform-forms-client/issues/696) 
These environment variables were added to support the new GC Notify service for Staging. 
- GC_NOTIFY_URL 
- TEMPLATE_ID
- TEMPORAY_TOKEN_TEMPLATE_ID

Add a second gc notify service

---

aws/app/lambda/local_development/template.yml

- Just a simple change to make sure our Lambdas are running on NodeJS 14 locally (instead of 12)

fix: make local lambdas use NodeJS 14 runtime instead of 12

---

aws/app/lambda/templates/templates.js

Allows `LIMIT` and `OFFSET` to be passed as parameters to be used as keywords in the SQL statement for GET requests. This will limit the number of rows returned, so that the amount of data returned by the lambda function is under the 1MB limit.
Addresses Issue cds-snc/platform-forms-client/#786
This will need PR 791 in `platform-forms-client` to be tested.

fix: add `limit` and `offset` parameters

---

.github/workflows/generate-sbom.yml

Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
* cds-snc/platform-sre-security-support#94

feat: generate Software Bill of Materials

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/scripts/init_localstack/localstack-entrypoint.sh
.devcontainer/scripts/terraform_apply_localstack.sh
.gitignore
Makefile
README.md
aws/app/lambda/start_local_lambdas.sh
env/common/local-provider.tf
env/local/app/.terraform.lock.hcl
env/local/app/terragrunt.hcl
env/local/kms/.terraform.lock.hcl
env/local/sns/.terraform.lock.hcl
env/local/sqs/.terraform.lock.hcl
env/staging/env_vars.hcl
env/terragrunt.hcl

devcontainer updated to allow running localstack from within the container. AWS SAM still needs to be launched from outside the devcontainer due to issues with mounting within a docker-in-docker setup.
To launch the lambdas you can run the new `make lambdas` command while in the root directory from outside the devcontainer as long as you have aws sam installed.
Tested to confirm the localstack setup works the same when using a devcontainer or when running directly on our machines.

feat: use latest localstack and run in devcontainer

---

aws/app/lambda/start_local_lambdas.sh

Update the `make lambdas` target so that it can correctly
identify zombie and reaped `dind_add_host.sh` script
processes so that they are restarted.
Prior to this change, a `<defunct> dind_add_host.sh` was
considered running.

fix: detection of zombie dind_add_host script

---

aws/app/lambda/reliability/lib/dataLayer.js

This PR fixes an error that we are seeing in AWS Staging where DeleteItemCommand is referenced in code block but is not imported into the function from the AWS module.

Add missing import in Reliability Queue Data Layer

---

aws/app/lambda/local_development/template.yml
aws/app/lambda/reliability/lib/vaultProcessing.js

No issue for this just a bug that currently exists in staging
* Declare fileInputPaths so it's available to the whole function block
* Remove Promise.all as it functionally provides no purpose in an async function other than to bunch up the individual promises into one
* Fix AWS SAM template to account for changes ( region ) 
1. Run localstack 
2. Create test form that has the submission set to vault mode
3. Submit form
4. Invoke reliability queue and there should be no errors

fix: block scoped variable called in other block

---

aws/app/s3.tf

Update the Vault S3 bucket to enable versioning.  This will
help prevent accidental deletion of objects by console
and CLI users.

feat: enable versioning on Vault S3 bucket

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Makefile

1. Update the Node.js version in the devcontainer so it meets
the version constraints of the new lambda dependencies.
2. Update the Makefile targets to remove lambda deps before
running the localstack Terragrunt commands.  This is done
to avoid the `node_modules` folders in the `.terragrunt-cache`
folder, which slows down the Terragrunt apply command.
3. Remove the manual `$PATH` update since it is not required and
was breaking the Node.js devcontainer feature in `zsh`.
1. Open the project in the devcontainer.
2. Test that the following commands work:
```sh
node -v
npm -v
yarn -v
```
3. Build the local infrastructure and start the lambdas:
```sh
make terragrunt
make lambdas
```

fix: devcontainer Node.js version

---

aws/app/lambda/local_development/template.yml
aws/app/lambda/reliability/lib/templates.js

- Add missing database environment variables 
- Fix the prepared statement used to retrieve form data.
- Update error logging to use `util.inspect`.  `JSON.stringify(err)` 
was only showing empty objects `{}` in the logs compared to 
`util.inspect` which shows the underlying error:
```javascript
// JSON.stringify(err)
{"status": "error", "error": "{}"}
// util.inspect(err)
{"status": "error", "error": "Error: Missing Environment Variables at processTicksAndRejections (internal/process/task_queues.js:95:5)"})
```
1. Start local dev environment with `make terragrunt && make lambdas`.
2. Start platform forms client with `yarn dev`.
3. Perform a form submission.
4. Use `./aws/app/lambda/invoke_reliability.sh $SUBMISSION_ID` to trigger
the Reliability lambda.
* …

fix: local Reliability lambda execution

---

aws/app/ecs.tf
aws/app/ecs_iam.tf
aws/app/ecs_task/form_viewer.json

Update the Form Viewer ECS task to grant read access to the Vault
S3 bucket objects and their tags.  
This will be used by the file scanning API endpoints to download 
form attachments and list the antivirus scan metadata which is 
stored as S3 object tags.
Once the file upload API endpoints are finished:
1. Submit a form that includes file attachments.
2. Request the file antivirus scan metadata.
3. Download the form submission's files.
* cds-snc/platform-forms-client#837

feat: Form Viewer read Vault S3 objects

---

aws/cognito/user_pool.tf

Fixes an error thrown by terraform when creating a cognito user pool.  Even though SMS will not be used a message needs to be defined if using the 'invite_message_template' doc.  This is a known issue even if Terraform AWS documentation states the field as optional.  
https://github.com/hashicorp/terraform-provider-aws/issues/13060

Added sms_message even though it will not be used

---

aws/cognito/user_pool.tf

The cognito user pool was created sucessfully however was not generating a Client Secret that could be stored in the Secret Manager.  This change ensures a secret is created.

Add property to generate user pool secret

---

aws/alarms/cloudwatch.tf

closes https://github.com/cds-snc/platform-forms-client/issues/918
- Added alarm when a temporary token request is made using an unauthorized email address (will send a Slack message on forms-deploy-activities)

feat: alarm when temporary token is requested using unauthorized email address

---

aws/cognito/user_pool.tf

- Enable AWS Cognito hosted UI by adding a Cognito domain.
- Added secondary callback URL to allow developers to run local test with Cognito

feat: enable AWS Cognito hosted UI

---

aws/load_balancer/kinesis.tf
aws/load_balancer/locals.tf
aws/load_balancer/waf.tf
aws/network/vpc_flow_log.tf

Update the VPC flow logs and WAF ACL logs to send to the Cloud Based Sensor satellite bucket.
The existing log bucket and CloudWatch log group can be deleted once their lifecycle rule and retention period have elapsed.
* Closes cds-snc/cloud-based-sensor#86

feat: send VPC and WAF logs to Cloud Based Sensor

---

aws/load_balancer/kinesis.tf
aws/load_balancer/locals.tf
aws/load_balancer/waf.tf
aws/network/vpc_flow_log.tf

Update the VPC flow logs and WAF ACL logs to send to the Cloud Based Sensor satellite bucket.
The existing log bucket and CloudWatch log group can be deleted once their lifecycle rule and retention period have elapsed.
- #253

feat: send VPC and WAF logs to Cloud Based Sensor (#253)

---

README.md
aws/app/lambda.tf
aws/app/lambda/archive_form_templates/archiver.js
aws/app/lambda/invoke_archive_form_templates.sh
aws/app/lambda/local_development/template.yml
aws/app/lambda/reliability/lib/templates.js

linked to https://github.com/cds-snc/platform-forms-client/pull/1179
- Added a new lambda function that runs on a daily basis in order to delete form templates that have been marked as archived
- Delete a form template using the admin UI
- Using the `yarn prisma:studio` database UI you can modify the `ttl` DateTime value (that is currently in the future) of the form you have deleted in order to put a date that is in the past
- Run the `archive_form_template` lambda function locally (see README.md)
- The form template should now be deleted from the database

feat: add lambda function to delete archived form templates

---

aws/app/cloudwatch.tf

- Fixed issue where the `archive_form_templates` lambda function was not properly connected to the `every-day-at-4am` CRON event

fix: archive form templates lambda function is missing a connection with the CRON event

---

aws/app/lambda/dead_letter_queue_consumer/dead_letter_queue_consumer.js

The DLQ redrive Lambda was incorrectly creating new messages leading to errors that the Reliability Queue could not find the submission to retry.
Each subsequent message was being created with an additional layer:
`{"submissionID":"{\"submissionID\":\"{\\\"submissionID\\\":\\\"edab5fe5-0e16-445d-851e-d057156fd0f6\\\"}\"}"}`
Instead of:
`{"submissionID":"edab5fe5-0e16-445d-851e-d057156fd0f6"}`

Fix DLQ Queue

---

renovate.json

Update the Renovate config so that non-major GitHub action and Docker digest update PRs are grouped together.
I've been testing these suggestions since our feedback session last week and they're working well to cut down on the PRs.
- cds-snc/platform-core-services#182

feat: group Docker and GitHub Renovate updates

---

.github/workflows/terragrunt-apply-staging.yml

- Added `workflow_dispatch` event to Apply Staging workflow file. The goal is to allow us to manually deploy in staging in case we change something like a Github secret.

feat: added workflow_dispatch option to Apply Staging workflow file

---

aws/load_balancer/waf.tf

This PR removes dynamic logic to ensure that Staging is an accurate representation of Production.

Remove logic creating 2 different WAF settings for Prod and Staging

---

aws/cognito/lambda_iam.tf
aws/cognito/user_pool.tf

permissions for cognito to access lambda

fix: only use supported lambda_version value in userpool

---

aws/cognito/user_pool_iam.tf

Adds an IAM role to allow Cognito to write logs to CloudWatch during a user import action.

Add role for cognito userpool import logging

---

aws/app/lambda/local_development/template.yml
aws/app/lambda/reliability/lib/markdown.js
aws/app/lambda/reliability/lib/notifyProcessing.js
aws/app/lambda/reliability/lib/templates.js
aws/app/lambda/reliability/lib/vaultProcessing.js
aws/app/lambda/reliability/reliability.js
aws/app/lambda/submission/submission.js

platform-forms-client pull request connected to that work: https://github.com/cds-snc/platform-forms-client/pull/1548
- Adapted code to new Template DB schema rework
- Make sure your client is connected to your Localstack backend
- Create a form and add a delivery email address to it
- Fill out that form and get the `submissionId` from the submission lambda output (logs)
- Run the reliability lambda using the `submissionId`
- When we release that change in production there is possibility that if a form is in the process of being processed by the reliability queue we would end-up getting a failure that would not be easily recoverable. We could add more code to handle that scenario but I would like to have your inputs first.

feat: adapt code to benefit from Template DB schema rework

---

README.md
localstack_services.sh

Updates the instructions to clearly indicate steps between Dev Containers and running without Dev Containers.
Also adds a script that runs terragrunt and starts lambdas for local development at the root of the project.

Update instructions and add a new script

---

.prettierrc.json
README.md
aws/app/lambda/reliability/lib/dataLayer.js
aws/app/lambda/reliability/lib/notifyProcessing.js
aws/app/lambda/reliability/reliability.js
aws/sqs/sqs.tf
localstack_services.sh

closes cds-snc/platform-forms-client#1582
This PR adds a new field to the Reliability Queue Submission record that tracks if it has already been processed by Notify.
This ensures that if there is an error between polling and deleting the message from SQS the submission will be identified as already processed.
This only applies to Submissions that are processed by Notify.  Submissions processed by the Vault are instantly deleted from the Reliability queue when moved to the Vault.
**Clean Up:**
- Add a prettierrc.json so that all projects use the same formatting to reduce the number of unrelated code changes in PR's
- Modify the readme to use `ca-central-1` for the AWS Region in the client.  Otherwise the dynamodb will not function correctly when being called from the app.
- Update the SQS …

Fix: Ensure no duplicate responses are sent through Notify

---

aws/app/lambda/invoke_reliability.sh
aws/app/lambda/invoke_reliability_single.sh
localstack_services.sh
start_dev_env.sh

Fixes:
- A logic problem in the script `localstack_services`.  The 'clean' flag was not being triggered
Adds:
- A new script `start_dev_env` that is a quick shortcut to run localstack and lambdas in a single terminal.  This command only works if you've previously run `localstack start` and `localstack_services` separately at least once before.
Modifies:
- The script `invoke_reliability.sh` no longer requires the submission ID.  It will connect to the SQS in LocalStack, pull the messages, and process them to the Reliability Lambda.

Launch Script + Reliability Invoker

---

aws/app/lambda/archive_form_responses/archiver.js

- Converted number to string in dynamodb query inputs

fix: converting number to string while making dynamodb query

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/sqs/outputs.tf
aws/sqs/sqs.tf
env/production/alarms/terragrunt.hcl
env/staging/alarms/terragrunt.hcl

- Adds an alarm for when messages are sent to the Audit Log DLQ
- Modifies existing alarm for reliability DLQ.  Alarm will not reset until messages are cleared.
- Adds redrive policy so that Audit Log messages can be retried through the AWS Management Console and removes the requirement for an additional lambda function.
closes #342

Add alarm for Audit Log DQL and Redrive policy

---

aws/app/inputs.tf
aws/app/lambda.tf
aws/sqs/outputs.tf
env/local/app/terragrunt.hcl
env/production/app/terragrunt.hcl
env/staging/app/terragrunt.hcl

Fixes rename for the Reliability DLQ that was missed in an earlier PR.

Fix missing rename in app module for lambda

---

aws/load_balancer/waf.tf

Moves the BlockInvalidURL rule up higher in the priority so that it can filter our more traffic before testing for more granular AWS managed rules.

Change waf rule order

---

aws/app/lambda.tf

- Fixed `archive_form_templates` lambda unable to import lib (`templates`) dependency

fix: archive form templates lambda unable to find lib dependency

---

aws/app/lambda/nagware/lib/postgreSQLDataLayer.js

- Fixed issue with SQL parsing for Nagware lambda (LocalStack vs AWS)

fix: dynamic parsing for Nagware SQL response depending on environment (LocalStack vs AWS)

---

aws/app/lambda.tf

- Increased nagware lambda timeout to 300 seconds (from 3). Two days ago our lambda started to reach that timeout limit.

fix: increased nagware lambda timeout

---

aws/app/lambda/nagware/lib/emailNotification.js

- Added condition to ignore GC Notify safelist error when Nagware lambda runs in staging

feat: nagware lambda now ignores GC Notify safelist error in staging

---

aws/cognito/lambda/cognito_email_sender/cognito_email_sender.js

- Re-added `accountVerification` and `resendCode` to the GC Notify `personalisation` object. They are still required by the GC Notify email template. We could have removed them from the template but since we are still early in the development process of the 2FA feature we never know what will happen. We may need them back at some point...

fix: missing variables in GC Notify call when Cognito tries to send emails

---

aws/alarms/cloudwatch.tf

closes https://github.com/cds-snc/platform-forms-client/issues/2150
Goes with https://github.com/cds-snc/platform-forms-client/pull/2227
- Add new 2FA alarm for when a user is locked out because of too many verification failed attempts

feat: added new 2FA alarm for when a user is locked out because of too many verification failed attempts

---

aws/load_balancer/lb.tf

In preparation for the auto-change log on platform-forms-client change the load balancer health check to monitor a dynamic page like '/form-builder/edit' which is rendered on every call and is a better test of the viability of the application.

chore: use form-builder edit page for health check

---

aws/pr_review/iam.tf

Update the PR review environment's IAM role to allow it to attach to a VPC.  This is needed as it will then allow the lambda function access to the forms VPC resources, as allowed through the resource security groups.
- cds-snc/platform-core-services#378

fix: allow Lambda forms client VPC access

---

aws/rds/rds.tf

I'd like to retry the in place engine upgrade of #399.
The AWS [upgrade chart](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_UpgradeDBInstance.PostgreSQL.html) shows that we should be able to go from version 11.16 to version 13.9.  The original PR attempted to upgrade to version 13.6, which is impossible for version 11.16.
This PR also enables the major version upgrade by including the `allow_major_version_upgrade = true` switch.
The PR planning should show an in place engine update and not a destroy event.

chore: update engine to 13.9 and allow major version upgrade

---

aws/app/outputs.tf
aws/pr_review/inputs.tf
aws/pr_review/lambda.tf
env/cloud/pr_review/terragrunt.hcl

Add Lambda permission resource that allows the PR review environment lambda functions to invoke the Submission lambda.
- cds-snc/platform-core-services#378

fix: allow PR review env invoke Submission lambda

---

aws/pr_review/lambda.tf

Update the Submission lambda function permissions to grant the PR review env's IAM role the ability to invoke the function.
- cds-snc/platform-core-services#386

fix: Submission lambda permission for PR review env

---

aws/app/vault_scan_object.tf

Upgrade the `S3_scan_object` module to use the SQS queue to deliver S3 object events to Scan Files.
This change was made to support Notify's high load of async file scanning and in performance testing, behaves much more consistently than the transport lambda used in the previous version of the module.
Once this has merged, a change will be needed to the Scan Files API to have it use the new SQS queue as a source of S3 events.
- cds-snc/platform-core-services#380

feat: upgrade S3_scan_object to SQS queue

---

aws/alarms/cloudwatch.tf

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

fix: permission for Cloudwatch to run Notify Slack lambda

---

aws/alarms/athena.tf
aws/app/vault_scan_object.tf

Update the Terraform module version references so they are in the [correct format](https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories): 
> If the source address has arguments, such as the ref argument supported for the version control sources, the sub-directory portion must be before those arguments:
This will allow Renovate dependency PRs to update the module versions without stripping the `//sub-directory` path.
All modules have been upgrade to their latest compatible versions.

fix: Terraform module version reference

---

aws/load_balancer/waf.tf

Fix WAF invalid parameter exception error on regex pattern set due to invalid syntax

fix: waf regex invalid syntax

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml

- Use valid ReCaptcha public site key for production environment. Private key was updated in repository secrets.

fix: use valid ReCaptcha site key for production environment

---

aws/load_testing/lambda/Dockerfile

Updates python image for load testing lambda to 3.11 and ensures invokust compilation by installing Development Tools at build time.

chore: upgrade python image

---

aws/app/ecs_task/form_viewer.json

Adds missing entry under secrets in ECS task

fix: Add missing freshdesk api key to ecs task

---

aws/app/ecs_iam.tf

Fix IAM permissions to allow ecs to access freskdesk scret

fix iam permissiosn for freskdesk secret

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-staging.yml

Add a failure step to the Staging and Production Terraform apply workflows that will post a message to the appropriate `#forms-production-events` or `#forms-staging-events` channel if the workflow fails.
Additionally, remove the `pr_review` module filter condition from the Staging Terraform workflows. This will ensure that the `pr_review` module is always run during a Terraform apply and that its security groups are properly created.
- https://github.com/cds-snc/platform-core-services/issues/441

feat: notify Slack if Terraform apply fails

---

aws/sqs/sqs.tf

Fixes an issue where the GC Forms app could not properly send audit logs that were larger than 2048 bytes.

fix: SQS Max Message size to 256kb

---

.github/workflows/release_generator.yml

Update the release generator workflow to properly
reference the SRE app ID.
- https://github.com/cds-snc/platform-core-services/issues/441

fix: release generator token step

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.gitignore

Update the Slack webhook URLs in the Terraform apply workflows to include the protocol and host.
Update .gitignore to ignore `.env` files.

fix: format of TF workflow Slack webhook URL

---

aws/load_balancer/waf.tf

- Fixed regex for site verification files

fix: site verification files allowed path were not properly included in regex

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/app/ecs.tf
aws/app/lambda.tf
aws/cognito/user_pool.tf
aws/hosted_zone/hosted_zone.tf
aws/load_balancer/certificates.tf
aws/load_balancer/route53.tf
aws/load_balancer/waf.tf
aws/load_testing/lambda.tf
env/cloud/alarms/terragrunt.hcl
env/cloud/load_balancer/terragrunt.hcl
env/common/common_variables.tf
env/terragrunt.hcl

ACM certificate not being lifecycled to include new domain names.

fix: ACM cert not being recreated on domain name addition

---

env/cloud/alarms/terragrunt.hcl
env/cloud/load_balancer/terragrunt.hcl
env/terragrunt.hcl

Changes the default local value for the domains array to use double quotes.

fix: Needed to use double quote on domain local placeholder

---

README.md
aws/alarms/cloudwatch.tf
aws/app/lambda/invoke_test_vault_data_integrity_check.sh

- Updated README file to reflect changes in Localstack and AWS SAM CLI versions
- Adjusted threshold for new IteratorAge alarm
- Fixed issue in payload being passed to the Vault data integrity check lambda when running locally

fix: update to README file, adjust iterator age alarm threshold and fix to vault data integrity check local lambda test script

---

aws/load_balancer/cloudfront.tf
aws/load_balancer/route53.tf
aws/load_balancer/s3.tf
aws/load_balancer/static_website/index.html

closes https://github.com/cds-snc/forms-terraform/issues/29
- Added infra resources to redirect users to a static maintenance page when system is down or under maintenance mode
Note: since this cannot be tested locally, I expect changes/fixes to be required after we merge this as there will probably be stuff missing in the configuration of resources.

feat: redirect to static maintenance web page when in maintenance mode or service is down

---

aws/load_balancer/cloudfront.tf
aws/load_balancer/s3.tf

- Fix for maintenance mode deployment issues on AWS

fix: maintenance mode deployment issues second try

---

aws/load_balancer/certificates.tf
aws/load_balancer/cloudfront.tf
aws/load_balancer/route53.tf
aws/load_balancer/waf.tf

- Added basic WAF rule to only allow GET request on "/" for the Cloudfront distribution
- Added missing certificate for our Cloudfront distribution
- Health check now targets load balancer DNS address

fix: missing WAF rule and certificate. Health check now targets load balancer DNS

---

aws/load_balancer/waf.tf

- Fixed missing provider in new WAF rule for Cloudfront.

fix: missing provider in waf rule

---

aws/load_balancer/route53.tf

- Disable health check until maintenance mode implementation is finalized

feat: disable health check until maintenance mode implementation is finalized

---

aws/app/lambda/nagware/lib/emailNotification.js

Switch to "sign off" language rather than "confirm" language as per new interface copy.

Update email notification for overdue responses 

---

aws/alarms/cloudwatch.tf

Intregrity alarm treats no data as non-breaching
Fixes:

fix: intergrity alarm

---

aws/app/outputs.tf

Adds missing iam_role for ecs task to output of app module

fix: Add missing output to app module

---

aws/lambdas/vault_integrity.tf

- Enable code signing for the Vault data integrity check lambda

fix: enable code signing on Vault data integrity check lambda

---

aws/load_balancer/waf.tf

- Fixed wrong scope in WAF rule for maintenance mode

fix: WAF rule for maintenance mode not having proper scope

---

aws/load_balancer/waf.tf

- Added missing provider in WAF regex pattern set

fix: missing provider in WAF regex pattern set

---

aws/lambdas/iam.tf
aws/lambdas/inputs.tf
aws/lambdas/nagware.tf
aws/lambdas/reliability.tf
aws/secrets/outputs.tf
env/cloud/app/terragrunt.hcl
env/cloud/lambdas/terragrunt.hcl

- Fixed GC Notify API key not being properly passed (string instead of ARN) to Nagware and Reliability lambdas
- Removed `token_secret` from lambda module as it was not used
What happened:
With the new infra rework we did not take into account the fact that two of our lambdas were using the string value of the GC Notify API key secret. We converted it to an ARN value but the code does not know how to handle such value.
Note: We could definitely rework that at some point by adding an extra request to go get the secret value using the ARN.

fix: GC Notify API Key is not properly passed to Nagware and Reliability lambdas

---

aws/alarms/cloudwatch.tf
aws/lambdas/code/nagware/yarn.lock
aws/load_balancer/waf.tf

Setting up a warning alarm (for now) on out of country access since it could be an indicator of a compromised account.
https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3008
---
This pull request introduces a new rule to the current GC Forms WAF ACL, which identifies and counts instances where a public servant user is attempting to sign in from outside Canada. 
Additionally, it sets up a new CloudWatch alarm to send a warning notification to the team when the count exceeds 0 within a 1-minute period.
- You will need a VPN that allows you to connect via a different country (like ExpressVPN).
- Pick a country other than Canada.
- Go to the forms login page and attempt a sign-in.
- Check the Slack channel for a notification.

feat: add new cloudwatch alarm and waf rule for Cognito login outside Canada

---

aws/alarms/cloudwatch.tf

The AWS WAF appends a Region dimension when publishing the metric which was missing in the configuration of the CloudWatch alarm
https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html
Related to https://github.com/cds-snc/forms-terraform/pull/558

fix: add region dimension to the alarm metric configuration

---

aws/file_scanning/vault_scan_object.tf

Update the Scan Object integration to send Forms Staging file scans to the Scan Files Staging environment.
This will ensure that Staging environment performance and penetration testing does not impact the Scan Files Production service.

fix: split Staging/Prod use of Scan Files service

---

aws/s3/s3.tf

Removes the "private" acl block as it is not compatible with Enforced Bucket Ownership.

fix: ACL not compatible with Owernship Controls

---

aws/load_balancer/s3.tf

Remove S3 ACL that conflicts with bucket ownership enforcement.

Fix: Missed an S3 ACL on previous PR

---

.github/workflows/terragrunt-plan-all-staging.yml
aws/oidc_roles/iam_roles.tf

Update the release OIDC roles to use tag references as GitHub does not consistently pass the workflow's event name as part of the role assume request.
Update the Terraform plan all workflow to use the default `forms-terraform-plan` role.
- https://github.com/cds-snc/platform-core-services/issues/512

fix: GitHub workflow OIDC role claims

---

aws/cognito/lambda/cognito_email_sender/cognito_email_sender.ts
aws/lambdas/code/nagware/lib/emailNotification.ts
aws/lambdas/code/reliability/lib/notifyProcessing.ts

- Fix initialization of NotifyClient object

fix: initialization of NotifyClient is not working because of the way we pass the API key

---

aws/oidc_roles/iam_policies.tf

Update the PR review environment's OIDC role so that it can create the lambda functions in the VPC.
This was applied locally to test.
- https://github.com/cds-snc/platform-core-services/issues/512
- https://github.com/cds-snc/platform-forms-client/pull/3116

fix: PR review OIDC role for VPC lambda deploys

---

aws/dynamodb/dynamo.tf

closes https://github.com/cds-snc/forms-terraform/issues/561
- Enable deletion protection on all DynamoDB tables

feat: enable deletion protection on all DynamoDB tables

---

.gitignore
aws/lambdas/code/deps.sh
aws/load_balancer/route53.tf
env/cloud/alarms/terragrunt.hcl
env/cloud/app/terragrunt.hcl
env/cloud/cognito/terragrunt.hcl
env/cloud/lambdas/terragrunt.hcl
env/cloud/s3/terragrunt.hcl

Update the Terragrunt mock values so that the Production release can properly run `terraform plan`.
Update the `load_balancer` module to only expect a single hosted zone.  This is a temporary workaround while the `forms-formulaires.canada.ca` hosted zone still exists as a `hosted_zone` output and can be removed after the release.
Update the deps.sh script to also remove the lambda function `/dist` folders.
Remove the `import` blocks as these will be run using a script before the `terraform apply`.
- https://github.com/cds-snc/platform-core-services/issues/528

fix: update Terragrunt mock values to fix TF plan

---

env/cloud/lambdas/terragrunt.hcl

Update the `lambdas` module to include an `import.tf` that is only generated for prod releases.
- https://github.com/cds-snc/platform-core-services/issues/528

chore: create production `import.tf` file

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml
aws/app/ecs.tf

Update the ECS autoscaling target so that the Form viewer task will scale as expected with CPU and memory load.
Update the TF apply production workflow to use the new OIDC release role.
- https://github.com/cds-snc/platform-core-services/issues/512
- https://github.com/cds-snc/forms-terraform/pull/526

fix: ECS service autoscaling target

---

aws/load_testing/lambda.tf
aws/load_testing/lambda/tests/locust_test_file.py

Update the Lambda load test's environment variable configuration.
Remove the load test's form submission test as this is currently blocked by the CSRF and recaptcha protection.
The environment variable changes were made in the AWS console to test which is why there are no TF plan changes.

fix: load test env vars and test file

---

aws/dynamodb/dynamo.tf

- Disable TTL for DynamoDB Audit logs table

chore: disable TTL for Audit logs DynamoDB table

---

.env.example
.gitignore
README.md
localstack_services.sh

In order to make it less annoying for us to deploy the infra without having to make sure all environment variables are properly set in the terraform files I decided to add a `.env` file with a mechanism to load them when we call the `localstack_services.sh` script.

chore: create env file that gets automatically loaded when we start the infra in Localstack

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/lambdas/cloudwatch.tf
aws/lambdas/code/nagware/nagware.ts
aws/lambdas/form_archiver.tf
aws/lambdas/nagware.tf
aws/lambdas/reliability.tf
aws/lambdas/reliability_dlq_consumer.tf
aws/lambdas/response_archiver.tf

related to https://github.com/cds-snc/platform-forms-client/issues/3202
- Added new free disk space step in some of the Github workflows (more information below)
- Renamed lambda trigger resources
- Reworked Nagware to always send emails no matter how old is the detected form response. Nagware will now run on Tuesdays, Thursdays and Sundays. It will only send email on Tuesday and Thursday and will send Slack notifications on Sunday.
- Added missing environment variable in Nagware and Form archiver lambdas (to reach PostgreSQL while running in Localstack)
For some reason that still need some investigation, our Github workflow (`terraform-plan-staging`) has started reaching the limit of the Github runner disk space. There are multiple people on the internet that have encountered the same …

chore: reduce number of Nagware emails and Slack notifications

---

aws/dynamodb/dynamo.tf

- Removed TTL resource block on DynamoDB Audit logs table since it was disable in both Staging and Production and now causes a conflict when being deployed on AWS
```
╷
│ Error: updating Amazon DynamoDB Table (AuditLogs): updating Time To Live: ValidationException: TimeToLive is already disabled
│ 	status code: 400, request id: DLKAF6N0BFHNB0T8S5GQ87SUUJVV4KQNSO5AEMVJF66Q9ASUAAJG
│ 
│   with aws_dynamodb_table.audit_logs,
│   on dynamo.tf line 92, in resource "aws_dynamodb_table" "audit_logs":
│   92: resource "aws_dynamodb_table" "audit_logs" {
│ 
╵
```

fix: deployment issue due to audit logs TTL resource block that is not needed anymore

---

aws/lambdas/cloudwatch.tf

- Fixed Nagware lambda trigger CRON definition

fix: nagware lambda trigger CRON definition is incorrect

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/lambdas/outputs.tf
env/cloud/alarms/terragrunt.hcl

- Adds missing subscription filter to audit logs archiver lambda logs

fix: add missing subscription filter to audit logs archiver lambda logs

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
README.md
aws/alarms/inputs.tf
aws/alarms/lambda.tf
aws/alarms/lambda/notify_slack/notify_slack.js
aws/app/inputs.tf
aws/lambdas/code/audit_logs/audit_logs.ts
aws/lambdas/code/submission/submission.ts

We want to utilize the Lambda function that currently notifies our Slack channel to also route SEV1 events to OpsGenie.
1. Drop a message with the word SEV1 on any SNS topic 
3. The lambda will be triggered and will analyse the log and create an alert in OpsGenie with some basic messaging

feat: send critical/error events to OpsGenie

---

aws/app/ecs.tf
aws/app/ecs_task/form_viewer.json

Renames the NEXTAUTH_URL parameter to HOST_URL as it is used in other parts of the application.
Future versions of Next-Auth (v5) have an issue when the NEXTAUTH_URL is present. Our current version (V4) does not explicitly require the NEXTAUTH_URL and can operate without it.
Dependency on: https://github.com/cds-snc/platform-forms-client/pull/3288

chore: Rename nextauth_url variable

---

docker-compose.yml

Increases the persistance snapshot window for localstack from 15 seconds to 60 seconds.
I found the 15 second window was causing a performance degradation when many actions (lambdas, DynamoDB queries, etc) were happening at once.  So far 60 seconds has been a good balance but we can definitely increase it again in the future if needed.

chore: Increase localstack snapshot delta

---

aws/app/ecs_task/form_viewer.json

Reverts cds-snc/forms-terraform#624
Found an issue that makes reference to why we need write access to local system when using yarn commands: https://github.com/nodejs/corepack/issues/183

Revert "fix: Container gets read-only access to its root file system."

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml

Default token was being used instead of token passed in through workflow

fix: Notify Callback Token using default

---

aws/lambdas/code/reliability/lib/dataLayer.ts

- Fixed issue where TTL field in the ReliabilityQueue DynamoDB table had a wrong type (should be a Number but was a String). Because of that the TTL feature was not able to delete items from the table.

fix: changed TTL field type from String to Number in ReliabilityQueue DynamoDB table

---

.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml

Update the name of the `TF_VAR` environment variable that sets the Notify callback bearer token value.
- https://github.com/cds-snc/forms-terraform/pull/634

fix: update name of Notify callback token TF variable

---

aws/s3/s3.tf

This should be applied before we merge https://github.com/cds-snc/forms-terraform/pull/626
- Set `force_destroy` to true on Lambda code bucket in preparation for the Lambda containerization upgrade which will delete this bucket

chore: set force_destroy to true on Lambda code bucket in preparation for the Lambda containerization upgrade which will delete this bucket

---

aws/lambdas/submission.tf

This reverts commit 66f98b92e41c52d0c2651fd11e9914d4cbc5517d.
- Change of plan! We are going to put back the old name for the Submission Lambda function as it is getting complicated to try to make that change happen smoothly in Production.

Revert "chore: add permission for ECS task to call legacy submission Lambda function name (#643)"

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml

- Adds missing `runs-on` property to Github workflow

fix: missing runs on property in Github workflow

---

lambda-code/cognito-email-sender/main.ts
lambda-code/cognito-email-sender/package.json
lambda-code/cognito-email-sender/yarn.lock
lambda-code/nagware/lib/emailNotification.ts
lambda-code/nagware/package.json
lambda-code/nagware/yarn.lock
lambda-code/reliability/lib/notifyProcessing.ts

Enhances the Notify error handling to be more consistent across the different Lambdas.
Also fixes a logic bug that may have resulted in less verbose information being presented in the logs after an Axios Error in the Reliability Queue / Notify Processing lib.
Logic issue:
```js
class AxiosError extends Error;
const notifyError = new AxiosError;
let errorMessage = "";
if (notifyError instanceof AxiosError) /* true */ {  
errorMessage = "I'm a detailed Notify Error message";
}
if (notifyError instanceof Error) /* true */ {
errorMessage = "I'm a generic error message";
}
console.log(errorMessage);
/* I'm a generic error message */ 
/* Desired behavior is "I'm a detailed Notify Error message" */
```

fix: Update Notify error handling across lambdas

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
README.md

- Fixed issue with Github workflow Terraform apply actions. We found a scenario where the Terraform modules were not applied because no detected changes in Lambda functions.

chore: Github workflow deployment script not working as intended

---

.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
.github/workflows/test-lambda-code/action.yml
.gitignore
lambda-code/notify-slack/package.json
lambda-code/notify-slack/tests/notify-slack.test.ts
lambda-code/notify-slack/yarn.lock

- Adds a new job in the Terraform plan Github workflows in order to run unit tests in Lambda code when available.

chore: added test-lambda-code job to Github workflow

---

lambda-code/notify-slack/package.json

- Fixes Notify Slack lambda function which was not working because of missing scripts in package.json

fix: notify slack lambda function had missing scripts in package.json

---

aws/load_balancer/waf.tf

The /api/auth/session endpoint isn't significant enough to raise suspicion of an out-of-country login, but the MFA endpoint might be—even though it still doesn't necessarily indicate that someone has actually logged in.

fix: include the mfa endpoint for WAF detection

---

.github/workflows/conventional-commit-lint.yml
.github/workflows/scripts/terraform-variable-check.sh
.github/workflows/terraform-variable-check.yml

Adds the following two workflows:
1. `conventional-commit-lint`: check all commits follow the conventional commit style.  This will help ensure that the Release Please changelog contains all PRs.
2. `terraform-variable-check`: checks that the GitHub workflow Terraform variables defined as `TF_VAR_` prefixed environment variables have a matching `variable` definition in the codebase.  This will help prevent accidental misconfigurations between the workflows and Terraform code.
Once this merges, if a PR contains any commits that do not follow the conventional commit style, those commit messages will need to be rewritten with `git rebase` or `git commit --amend`.

feat: add TF_VAR check and conventional commit lint workflows

---

.github/workflows/conventional-commit-lint.yml

Remove the conventional commit lint from PRs until we've determined if merge queues can be used to enforce the desired squash commit message style.
The workflow is being converted to a `workflow_dispatch` trigger so that it is easy to reference if we go to merge queues.
- #663

revert: remove conventional commit lint from PRs

---

aws/load_balancer/waf.tf

To mitigate the risk of a CSRF attack during form submission, a CSRF token is requested. Therefore, this is not an endpoint that needs to be monitored for sign-ins from outside the country.

fix: Remove CSRF regex pattern from WAF out-of-country rule

---

.github/workflows/terragrunt-apply-production.yml

- Removes load-testing lambda deployment from apply production workflow

fix: remove load-testing lambda deployment from apply production workflow

---

lambda-code/deploy-lambda-images.sh

- Fixes a Lambda deployment issue caused by one of the newer version of Localstack. It appears that we should now use the default Localstack port to communicate with ECR.

chore: fix Lambda deployment issue with Localstack

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml

The use of `always()` makes it impossible to cancel the workflow jobs. This change means that the workflow will still run as expected if jobs are skipped, but allow for cancel actions as well.
Additionally, the following changes have been. made: 
- The check on the `github.ref` has been removed from the Staging workflow as this workflow only triggers on push to the `develop` branch.
- Conditional `if: ${{ }}` syntax has been added back as GitHub is encountering a parsing error without it.
The following are the test results showing which jobs will execute depending on how they are skipped, cancelled or fail:
- https://github.com/cds-snc/platform-core-services/issues/574

fix: remove use of `always()` in the TF apply jobs

---

aws/alarms/athena.tf

Update the Terraform module to the version with a fix for how the Athena load balancer logs table is created.
- https://github.com/cds-snc/terraform-modules/pull/513

fix: Athena load balancer create table query

---

aws/alarms/metrics.tf

Add a CloudWatch metric filter for successful and failed form submissions through the client app.
- https://github.com/cds-snc/platform-forms-client/issues/3590

feat: add form submission health check metrics

---

.github/workflows/get-version/action.yml
.github/workflows/scripts/wait-for-tag.sh
.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-production.yml

Update the Production Terraform workflows so that a release can more easily be reverted.  Now all that will be required to rollback a failed release is to revert the Release Please PR.
The way this works is as follows:
1. When a PR that updates `version.txt` is opened, the TF plan workflow will check if it's a Release Please branch.  If yes, the branch is used to perform the TF plan.  Otherwise it is assumed to be a revert PR and the tag specified in `version.txt` is used for the TF plan operation.
2. On merge of a PR with a `version.txt` change, the TF apply workflow will wait for the git tag it specifies to exist.  For a normal release flow, this will be once the `release_generator` workflow finished.  For a revert PR, the tag will already exist.
Additionally, the code checkout step has …

feat: simplify production release reverts

---

.github/CODEOWNERS

With the new process where production Terraform apply is triggered by changes to the `version.txt` file, the codeowners should be updated so that these PRs require specific approvers.
This is enforced with branch protection rules on the `develop` branch:
- https://github.com/cds-snc/platform-forms-client/issues/3590
- https://github.com/cds-snc/forms-terraform/pull/678

chore: update codeowners to protect version.txt

---

aws/alarms/metrics.tf
lambda-code/form-archiver/main.ts
lambda-code/response-archiver/main.ts

Add CloudWatch metric filters for the following Lambda functions:
- Form archiver
- Reliability
- Response archiver
- Submission 
These will be used to build out dashboards and create health check alarms if success metrics are not observed consistency.
Add success log events and a `status` property to the form-archiver and response-archiver Lambda functions.

feat: add CloudWatch metrics for Lambda behaviour

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml

Add back the checkout step as this is needed so the local composite action definition is available for the job.

fix: checkout code for update lambda workflow step

---

aws/alarms/dashboards.tf
aws/alarms/dashboards/forms_service_health.tmpl.json
aws/alarms/inputs.tf
aws/rds/outputs.tf
env/cloud/alarms/terragrunt.hcl

Add a CloudWatch dashboard that displays the system health metrics, logs and alarms.  The goal is to make it easier for on-callers to identify where issues are occurring if they are paged.

feat: add system health dashboard

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml

Update the Terraform apply workflow to use the OIDC role that can be assumed by workflows running on the `develop` branch.
Update the Terraform plan workflow to always build and test all lambdas.
- #680

fix: use correct IAM role for TF apply

---

aws/oidc_roles/iam_roles.tf

Remove this role as it is no longer required.  Previously it was used to run Terraform apply against production when a release tag had triggered the workflow.
With the change to support release revert PRs, Terraform apply workflows against production are now triggered by pushes to the `develop` branch.
- https://github.com/cds-snc/platform-forms-client/issues/3590

chore: remove `forms-terraform-apply-release` OIDC role

---

aws/alarms/dashboards/forms_service_health.tmpl.json

Update the service health dashboard to use CloudWatch log insight queries to generate the graphs.

fix: switch dashboard to log insight graphs

---

aws/alarms/cloudwatch.tf
aws/alarms/inputs.tf
aws/alarms/locals.tf
env/cloud/alarms/terragrunt.hcl

Add alarms that will trigger if no submission lambda function invocations have been seen in an expected period.
- `SubmissionLambdaNoInvocationsCoreHours`: triggers if there has not been at least one invocation between 9am UTC and 6am UTC the next day.  Between 6am and 9am, the alarm will always be in a non-breaching state.
- `SubmissionLambdaInvocationsAnomaly`: uses anomaly detection and will trigger if the invocations are low for a given period.
Neither alarm has an SNS action defined.  This will allow us to observe and adjust their behaviour before they begin posting to Slack for a breaching state.

feat: health check alarm for submission lambda invocations

---

aws/app/ecs_task/form_viewer.json

Update the ECS task definition to include the default values that are added by AWS when the ECS task definition is created.
This will stop our TF plans from always showing an app change on all PRs.

fix: ECS task definition constant change on TF plan

---

lambda-code/nagware/lib/emailNotification.ts

Fixes https://github.com/cds-snc/platform-forms-client/issues/3914
Updates email template to match url structure that was released with the app router
Noting: 
https://forms-formulaires.alpha.canada.ca/en/form-builder/form-id-here/responses
will auto-redirect to 
https://forms-formulaires.alpha.canada.ca/en/form-builder/form-id-here/responses/new

fix: fix overdue response url

---

aws/idp/route53.tf
aws/idp/ses.tf
idp/docker/config.yaml

Add SES configuration and an IAM user so that the IdP can send email using the SES SMTP server.
Also updates the database configuration to add connection pool settings as we are currently not using an RDS proxy to manage the connection pooling.
- https://github.com/cds-snc/platform-forms-client/issues/3927
- https://github.com/cds-snc/platform-forms-client/issues/3925

feat: send IdP emails using SES SMTP server

---

aws/idp/route53.tf
aws/idp/ses.tf

Add email sending DNS records.  The purpose of each is as follows:
- `SPF`: specify which servers are authorized to send emails on behalf of the IdP domain.
- `DKIM`: verify that an email message was not altered during transit and that it came from the claimed sender.
- `DMARC`: specify how emails that fail SPF or DKIM checks should be handled. A report with emails that fail the checks will be sent to security@cds-snc.ca
- Closes cds-snc/platform-forms-client#3952

feat: add SPF, DKIM and DMARC DNS records

---

aws/alarms/athena.tf

Amazon Athena federated queries allow us to run SQL queries across data stored in various data sources without the need to move the data. This PR enables the integration between Athena and DynamoDB.
e.g. 
```select * from dynamodb.default.vault```

feat: Enable Amazon Athena to communicate with DynamoDB

---

aws/dynamodb/dynamo.tf

Ensures that only required keys are projected into the global index for the Vault.
This will help reduce the volume of write requests when downloading and confirming responses.

Fix: Updates global indexes to only project needed keys

---

aws/dynamodb/dynamo.tf

Modifies the Archive Global Index to project 'All' attributes instead of only those required by the function.  This is due to a seemingly impossible way to project a key that uses a reserved word.
This is also temporary as step 2 is to modify the Lambda functions to not use the indexes.

fix: Change the Archive Index key projection back to All

---

aws/alarms/cloudwatch_app.tf
aws/alarms/cloudwatch_idp.tf
aws/alarms/inputs.tf
aws/idp/outputs.tf
env/cloud/alarms/terragrunt.hcl

Add alarms for the IdP that trigger for:
- High resource use in the ECS and RDS clusters.
- Load balancer unhealthy hosts or slow responses.
- Errors logged by the IdP.
- SES bounce and complain rates.
Also removes the Submission lambda anomaly detection alarm as this will not meet our needs.  The predicted invocations is not accurate enough and would only result in a noisy alarm.
- cds-snc/platform-forms-client#3954

feat: add IdP CloudWatch alarms

---

env/cloud/alarms/terragrunt.hcl

Update the `alarm` module's Terragrunt configuration so that it can still apply if the `idp` module Terraform state does not exist.

fix: `alarm` module apply when `idp` not enabled

---

lambda-code/response-archiver/main.ts

- Fixed issue in response archiver lambda function. The scan operation should ignore confirmation code entries in the DynamoDB Vault table.

fix: response archiver lambda will ignore confirmation code entries in the DynamoDB Vault table when scanning for items

---

aws/idp/waf.tf

Update the IdP's WAF ACL to block all requests that do not have the expected `host` header.
This header value is used by Zitadel to lookup an instance that can process a given request.  If the value is incorrect, the lookup fails:
Request like the above can occur during fuzzing attacks when a script is checking to see if it can bypass controls by using the IP address directly.
This was applied locally to test.

fix: block invalid `host` requests to the IdP

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/api/ecs.tf
aws/api/inputs.tf
aws/ecr/ecr.tf
aws/ecr/outputs.tf
aws/network/outputs.tf
aws/network/security_groups_api.tf
aws/network/security_groups_app.tf
env/common/common_variables.tf
env/terragrunt.hcl

Add an API ECS service to the Forms cluster.  This also includes a new ECR to hold the API's Docker image.
As with the IdP, a feature flag has been added to control the creation of API infrastructure.  This will give us fine-grained control over when resources are created in each environment.
This PR will only create the ECR and API security group as the Terraform plan/apply workflows have not been updated yet to create the new API ECS service.

feat: add API ECS service to the Forms cluster

---

env/cloud/dynamodb/.terraform.lock.hcl
env/cloud/ecr/.terraform.lock.hcl
env/cloud/kms/.terraform.lock.hcl
env/cloud/lambdas/.terraform.lock.hcl
env/cloud/network/.terraform.lock.hcl
env/cloud/rds/.terraform.lock.hcl
env/cloud/redis/.terraform.lock.hcl
env/cloud/s3/.terraform.lock.hcl
env/cloud/secrets/.terraform.lock.hcl
env/cloud/sns/.terraform.lock.hcl
env/cloud/sqs/.terraform.lock.hcl
env/common/local-provider.tf
env/common/provider.tf

Upgrade to the AWS 5.59.0 provider version.

chore: upgrade to latest Terraform AWS provider

---

aws/network/security_groups_app.tf

Update the Forms load balancer security group rules so that they are standalone rather than inline blocks.
This will make rule management more consistent and prevent the rules from flip-flopping through Terraform applies.
As part of this change, `import` blocks have been added to ensure there is no downtime.

fix: convert LB security rules to standalone

---

aws/alarms/athena.tf

The Athena-DynamoDB connector infers the DynamoDB schema and stores the metadata in lowercase (because it eventually works with Glue to sync the metadata if needed). However, the IAM role policy is case-sensitive, so we need to allow it to permit lowercase table names. This is one of the workarounds we found. (h/t @patheard )

fix: Athena-DynamoDB connector policy

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/api/ecs.tf
aws/load_balancer/certificates.tf
aws/load_balancer/lb.tf
aws/load_balancer/locals.tf
aws/load_balancer/outputs.tf
aws/load_balancer/route53.tf
aws/load_balancer/waf.tf
aws/network/security_groups_api.tf
env/common/common_variables.tf
env/terragrunt.hcl

- Add a load balancer target group and listener rule to route traffic to the API. 
- Add a dedicated certificate for API requests.
- Update the API's port to 3001.

feat: add API load balancer target group

---

aws/load_balancer/certificates.tf
aws/load_balancer/lb.tf

Add a certification validation resource for the API so that the load balancer waits to add the new certificate until it is fully validated.
This will prevent timing failures when the API infrastructure is released to a new environment.

fix: create API certificate validation resource

---

.github/module-filter.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/api/ecs.tf
aws/api/inputs.tf
aws/load_balancer/lb.tf
env/cloud/api/terragrunt.hcl

Update the Staging Terraform workflows to create the API's ECS service in the Form's cluster.

feat: deploy API ECS service in Staging

---

aws/api/ecs.tf
aws/load_balancer/lb.tf
aws/load_balancer/waf.tf

Update the WAF ACL to allow the API's valid paths.
Update the load balancer target group's health check path.
Update the name of the API's ECS service to be consistent with the form-viewer naming convention.

fix: add API paths to WAF and fix healthcheck

---

aws/load_balancer/waf.tf

Update the app valid path regular expression to include the API valid paths. This is being done to prevent accidentally blocking valid paths since the combination of both ACL rules was blocking all traffic.

fix: combine API valid paths with app

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/rds/inputs.tf
aws/rds/secrets.tf
env/cloud/rds/terragrunt.hcl

Update the RDS connector to use a read-only user to query the database.
- https://github.com/cds-snc/platform-forms-client/issues/3586

feat: add read-only user for RDS connector

---

aws/network/security_groups_app.tf

Remove the security group rule import blocks as the import has been completed and these are causing issues with creating localstack environments.

chore: remove completed `import` blocks

---

aws/alarms/cloudwatch_api.tf
aws/alarms/inputs.tf
aws/api/outputs.tf
env/cloud/alarms/terragrunt.hcl

Add API CloudWatch alarms for errors, high resource use and slow load balancer response times.

feat: add API CloudWatch alarms

---

aws/idp/waf.tf

Add large request block rule that will block any request with cookies, headers or a request body larger than 8kb.  This is the maximum size that WAF ACLs can inspect, and so this rule prevents padding attacks.
Add the AWS common rule set.

feat: update IdP WAF to block large requests

---

.gitignore
env/cloud/rds/terragrunt.hcl

- Added `rds_connector_db_password` variable to RDS terragrunt.hcl file to avoid having to set it in our .env file

chore: added rds_connector_db_password variable to RDS terragrunt.hcl file

---

aws/idp/lb.tf

Update the IdP's load balancer target group to use HTTP1. This is being done because of a limitation with the Node library being used to send requests.

fix: switch IdP LB protocol to HTTP1

---

aws/idp/waf.tf

Update the IdP's WAf ACL to exclude the `EC2MetaDataSSRF_Body` rule as this is blocking the creation of new IdP apps.
- https://github.com/cds-snc/platform-forms-client/issues/3938
- https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html

fix: exclude EC2MetaDataSSRF_Body WAF ACL rule

---

aws/load_balancer/waf.tf

Update the WAF ACLs allowed paths to include the OpenAPI `/v1/docs` route.

chore: add OpenAPI doc route to WAF

---

aws/idp/ecs.tf
aws/idp/lb.tf
aws/idp/locals.tf
aws/idp/outputs.tf

Update the IdP load balancer to include an HTTP1 and HTTP2 target group.  An ALB listener rule has also been added to send all REST API requests to the HTTP1 target group, while the HTTP2 target group is responsible for forwarding all other traffic.
The ECS service has also been updated to register both target groups.
- https://github.com/cds-snc/platform-forms-client/issues/3938
- https://github.com/cds-snc/terraform-modules/pull/543

feat: add HTTP2 IdP target group

---

aws/idp/lb.tf

Update the IdP load balancer listener rule to also send requests to the `/.well-known/openid-configuration` endpoint to the HTTP1 target group.
⚠️ This was applied through the console to test.
- https://github.com/cds-snc/platform-forms-client/issues/3938

fix: IdP listener rule for well-known config

---

.github/workflows/release_generator.yml

Upgrade to latest Release Please action.  The action options are now set via its configuration file rather than action inputs.
- https://github.com/cds-snc/platform-forms-client/pull/4162
- https://github.com/googleapis/release-please-action?tab=readme-ov-file#upgrading-from-v3-to-v4

chore: upgrade to Release Please v4

---

aws/api/ecs.tf
aws/load_balancer/certificates.tf
aws/load_balancer/lb.tf
aws/load_balancer/outputs.tf
aws/load_balancer/route53.tf
env/cloud/alarms/terragrunt.hcl
env/cloud/api/terragrunt.hcl

Linked to https://github.com/cds-snc/forms-api/pull/18
- Renames ECS Task name from `form-api` to `forms-api` (also changes the name of some resources)

chore: rename ECS API task from form-api to forms-api

---

aws/api/ecs.tf
aws/idp/ecs.tf

Update the API ECS service to always use the latest ACTIVE task definition.  This allows us to manage the task deployments primarily through the CI/CD deployment workflows of the `cds-snc/forms-api` repo.
- https://github.com/cds-snc/platform-forms-client/issues/4128
- https://github.com/cds-snc/terraform-modules/pull/544

fix: set API service to use latest task def

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml

The workflow action was looking for the variables where they were instead stored as secrets. I moved the provider URL to a repo variable (i.e., it doesn't need to be encrypted) and fixed the action script to look for the secret for the admin key.

fix: Secrets vs variable

---

aws/alarms/cloudwatch_idp.tf
aws/alarms/inputs.tf
aws/idp/outputs.tf
env/cloud/alarms/terragrunt.hcl

Update the IdP load balancer alarms to include unhealthy host alarms for both the HTTP1 and HTTP2 target groups.
- https://github.com/cds-snc/forms-terraform/pull/762

chore: add alarms for all IdP LB target groups

---

README.md

- Adds missing prerequisite tool in our README file

chore: add AWS CLI prerequisite to README.md

---

lambda-code/reliability/lib/dataLayer.ts

The previous code was not attaching files from within a repeatingSet.
- Create a form with a fileInput in a repeatingSet. ie: [multiple-file-uploads-2024-08-12.json](https://github.com/user-attachments/files/16591895/multiple-file-uploads-2024-08-12.json)
- Configure the form to send by email.
- Test the form in Preview and attach one or more files in the repeatingSet.
- Use small files as we are still adjusting the post size limit

fix: Attach files from fileInputs in a dynamicRow

---

aws/api/ecs.tf

- Attaches permission to retrieve secrets to API ECS task

fix: attach permission to retrieve secrets to API ECS task

---

aws/api/ecs.tf

- Fixes permission to use DynamoDB not properly set in the ECS task configuration

fix: permission to use DynamoDB was not properly set in the ECS task configuration

---

aws/api/ecs.tf

- Fixes permission to use KMS not properly set in the ECS task configuration

fix: permission to use KMS was not properly set in the ECS task configuration

---

aws/network/security_groups_api.tf

Update the the security groups to allow the API to connect to the ElasitCache Redis cluster.
- https://github.com/cds-snc/platform-forms-client/issues/4215

feat: allow API to access Redis

---

env/cloud/secrets/terragrunt.hcl

Fixes a missing input variable for `secrets` when trying to initialize locally with LocalStack.

fix: add missing input variable for sentry api

---

aws/api/ecs.tf
aws/api/inputs.tf
env/cloud/api/terragrunt.hcl

Update the `api` module to set the `REDIS_URL` environment variable on the ECS task.
- https://github.com/cds-snc/forms-api/pull/38
- https://github.com/cds-snc/platform-forms-client/issues/4215

feat: add Redis URL to the API ECS task

---

aws/api/ecs.tf
aws/api/inputs.tf
aws/redis/outputs.tf
env/cloud/api/terragrunt.hcl

Update the API ECS task's `REDIS_URL` environment variable to include the protocol and port.
- https://github.com/cds-snc/forms-api/pull/38
- https://github.com/cds-snc/platform-forms-client/issues/4215

fix: API Redis URL add protocol and port

---

aws/app/ecs_iam.tf
env/cloud/app/terragrunt.hcl

Update the app's ECS IAM permissions to allow it to access the Sentry API key secret.

fix: ECS task to access to Sentry secret

---

lambda-code/cognito-email-sender/lib/gc-notify-client.ts
lambda-code/nagware/lib/gc-notify-client.ts
lambda-code/reliability/lib/gc-notify-client.ts

- Removes Axios instance implementation from GCNotifyClient

refactor: remove axios instance in GCNotifyClient

---

.github/workflows/request-ecs-service-to-use-new-image/action.yml
.github/workflows/terragrunt-apply-staging.yml
aws/idp/ecs.tf

Update the Staging Terraform apply workflow so that a new IdP image is only built, pushed and deployed if there have been changes to the `idp` folder.  This will fix the error we saw where the ECR image deletion policy removed an image that was in use.
Also updates the IdP service to always use the latest available task definition so that both Terraform and the ECS deploy job can manage the same ECS task definition without conflicts.

fix: deploy new IdP image if changes

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-staging.yml
idp/docker/Dockerfile

Upgrade to the latest patch of the 2.55.x releases: 
https://github.com/zitadel/zitadel/releases/tag/v2.55.6
Additionally, the Staging Terraform workflows have been updated to trigger when there is an `idp` folder change so that the new image can be tested and deployed.
- https://github.com/cds-snc/forms-terraform/pull/805

chore: upgrade Zitadel to v2.55.6

---

aws/lambdas/inputs.tf
aws/lambdas/nagware.tf
env/cloud/lambdas/terragrunt.hcl
lambda-code/nagware/lib/overdueResponseCache.ts
lambda-code/nagware/lib/redisConnector.ts
lambda-code/nagware/main.ts
lambda-code/nagware/package.json
lambda-code/nagware/yarn.lock

Update the Nagware function so that it caches the overdue response form IDs in Redis.  
This is being done to reduce strain on the DynamoDB table when loading a user's `/forms` page.
- https://github.com/cds-snc/platform-forms-client/issues/4234

feat: cache the Nagware overdue response form IDs

---

aws/lambdas/cloudwatch.tf
lambda-code/nagware/lib/overdueResponseCache.ts
lambda-code/nagware/main.ts

Update the Nagware function schedule so that it run everyday. This is being done so that the Redis cache of overdue responses is kept more up-to-date.
The logic of the Nagware has also been updated so that emails are still only sent Tuesday/Thursday and Slack messages posted on Sunday.
- https://github.com/cds-snc/platform-forms-client/issues/4234

feat: run Nagware every day

---

aws/load_balancer/waf.tf

Update the global request limit to 2,500 requests in a 5 minute period for the app's load balancer.  This is being done to handle traffic from large networks where multiple people will share the same IP address.

fix: increase blanket WAF ACL rate limit

---

aws/idp/rds.tf
idp/docker/config.yaml

Add an RDS Proxy to manage the database connections for Zitadel. This will help reduce strain on the IdP and database and allow for smoother load scaling.
- Closes https://github.com/cds-snc/platform-forms-client/issues/4216

feat: use RDS Proxy for IdP database connection pool

---

aws/api/ecs.tf
aws/api/inputs.tf
env/cloud/alarms/terragrunt.hcl
env/cloud/api/terragrunt.hcl
env/cloud/app/terragrunt.hcl
env/cloud/idp/terragrunt.hcl
env/cloud/network/terragrunt.hcl
env/cloud/pr_review/terragrunt.hcl
env/cloud/secrets/terragrunt.hcl

Allow API to access the RDS connection URL stored in secrets manager

Fix: Allow API to access RDS connection url secret

---

aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_app.tf
aws/alarms/cloudwatch_idp.tf
aws/alarms/dashboards.tf
aws/alarms/dashboards/forms_service_health.tmpl.json

Update the App, IdP and API unhealthy host alarms to only trigger warnings that post to Slack.
Add healthy host alarms that trigger SEV1 OpsGenie responses when a service has no healthy hosts.  This will currently only trigger an OpsGenie page for the App load balancer target groups.
- https://github.com/cds-snc/platform-forms-client/issues/4233

fix: add HealthyHostCount alarms to App, IdP, API

---

aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_app.tf
aws/alarms/cloudwatch_idp.tf

Remove the `ok_action` from the HealthyHostCount critical alarms.  The notify Slack function currently treats the `SEV1` string as an indicator that an OpsGenie page should occur.
⚠️ Note that I've pre-emptively removed the `ok_action` from the API and IdP alarms since they will become `SEV1` alarms once they go to prod.
- https://github.com/cds-snc/platform-forms-client/issues/4233

fix: remove OK actions from critical alarms

---

aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_app.tf
aws/alarms/cloudwatch_idp.tf

Update the App, API and IdP ECS CPU and memory alarms to use the `Maximum` statistic rather than `Average`.
This will make the alarms more responsive to individual ECS tasks that are overloaded.
- https://github.com/cds-snc/platform-forms-client/issues/4233

fix: use maximum CPU/memory stat for alarms

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml

Update the Terraform production workflows and configuration to create and manage the IdP resources and deployment.

feat: deploy IdP to production

---

aws/oidc_roles/iam_policies.tf
aws/oidc_roles/iam_roles.tf

Add a new OIDC role that will be used by the `cds-snc/forms-api` repository to authenticate and push Production API Docker images when a new GitHub release is published.

feat: create Forms API OIDC role for releases

---

idp/docker/Dockerfile

Upgrade to latest Zitadel release to see if that improves database performance issues we've been seeing under load.
- There are no breaking changes listed for the upgrade.
- The [@zitadel/node package](https://github.com/smartive/zitadel-node/releases/tag/v2.0.22) we're using only has patch releases we haven't taken in the App.
- The database migration will happen in isolation as we only have a single ECS task running.

chore: upgrade to Zitadel v2.62.0

---

idp/docker/Dockerfile
idp/docker/config.yaml

There appears to be a regression with Zitadel v2.62.0 where the configuration is not being read properly.  For now we can go to v2.61.1 and see if a fix is released for the problem.
As part of this change, the config string values are being quoted as recommended by the Zitadel docs.
- #832

chore: downgrade to Zitadel v2.61.1

---

idp/docker/config.yaml

Update the configuration to set the default OIDC access token expiry times.  These can be overridden in the console if needed.
Update the login policy to initially disable registration and enforce MFA for new instances.  These are being set to prevent abuse.

fix: set default OIDC token expiry times

---

aws/alarms/cloudwatch_idp.tf
aws/alarms/locals.tf

Update the IdP error log to suppress errors caused by the client cancelling their request before Zitadel has time to respond.

chore: suppress `context canceled` IdP errors

---

idp/docker/config.yaml

Update the instance config so that the access token and ID token expire after 30 mins.  This will improve security by providing less time that a leaked token can be abused.

chore: reduce Zitadel token timeout to 30 mins

---

lambda-code/notify-slack/main.ts

Update the `notify-slack` lambda function to check if the parsed JSON is actually a JSON object.
This will eliminate the Slack messages we see where the [expected log message format cannot be parsed](https://gcdigital.slack.com/archives/C05G75MNP4Z/p1726673820091379):
- [Example showing the parse failure](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAtgUwhAhgcwTAvDARFAS0SwB1cAmABnIBYBaSgTjoEYAOAFRYFYAuAZgBsvboIBaZGABsEANwRSsCAE7KQy+BDSlc0FFASIwsBAA8EwAK6FwMAGYoCMgCaTgKKTOU6A9AAsQRB9lSzAwFR8Ad3UAax8ALwIoFGcFBKSUtIJjFTAPHzkEY2h1BH8UMGcvH1lycsqvADo0EF5BckFJFTVvMggARyleGChlCtRgGzAYPxQIGA9lBBSATxgAIwQimFA4OCSDZxh1GDVPBCP1lGAYyQAHNQArCymsB5BnyYJwCEbLCBUEBY-FwAG4AFCgSCwR4QcAABRQyigAHk7AAZEBoACySFQGGw8Dx6AQjQgUgIwAQAApEMgSY1sqlTGjqbgAN64ACUXIhULhMkaUix1IAUgBlFEAOUadyRAOpsIRSNRGKxuPpGB5oKA …

fix: test if Notify Slack log message JSON is valid

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_idp.tf
aws/alarms/moved.tf
aws/ecr/ecr.tf
aws/ecr/moved.tf
aws/ecr/outputs.tf
aws/load_balancer/certificates.tf
aws/load_balancer/lb.tf
aws/load_balancer/locals.tf
aws/load_balancer/moved.tf
aws/load_balancer/outputs.tf
aws/load_balancer/route53.tf
aws/network/moved.tf
aws/network/outputs.tf
aws/network/security_groups_api.tf
aws/network/security_groups_app.tf
aws/network/security_groups_idp.tf
env/cloud/alarms/terragrunt.hcl
env/common/common_variables.tf
env/terragrunt.hcl

Remove the feature flags from the code as both services have now been deployed to Production.
The `moved.tf` files can be removed once this has been released to Prod.
- https://github.com/cds-snc/forms-terraform/issues/840

chore: remove IdP and API feature flags

---

aws/api/ecs.tf
aws/idp/ecs.tf

Update to the v9.6.6 `ecs` module which has a fix to stop removing the latest ECS task definition revision in the Terraform plan.  
This will make things clearer when reviewing the PRs as removing the revision has no impact to our setup where the task definition is primarily managed by other workflows.
- https://github.com/cds-snc/terraform-modules/pull/562

fix: upgrade `ecs` module to stop task revision flip-flop

---

aws/idp/waf.tf
aws/load_balancer/outputs.tf
aws/load_balancer/waf.tf

Update the IPv4 blocklist to use the module that will create and manage the IP addresses on the blocklist using a Lambda function.
On a schedule, the Lambda function will query the WAF logs and temporarily add any IP address that exceeds a threshold of blocked requests to the blocklist.
- Closes https://github.com/cds-snc/platform-forms-client/issues/4256
- https://github.com/cds-snc/terraform-modules/pull/563

feat: add module to manage IPv4 blocklist

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml

Added GitHub secret for Production Administration Key for Zitadel to allow the app to create and modify users.

chore: Add zitadel key for app

---

aws/alarms/locals.tf

Update the IdP's CloudWatch alarm filter pattern so that it includes logs with a capitalized `ERROR` term, while also omitting access token requests where the user has signed the JWT with an invalid private key.

fix: adjust IdP CloudWatch alarm error filter

---

aws/idp/ecs.tf

Update to the correct 8GB memory value.
- #854 

fix: IdP task memory value

---

env/cloud/idp/terragrunt.hcl

Increase the max ACUs available to the IdP's database to test if there's a performance bottleneck.

test: increase IdP RDS resources

---

aws/idp/ecs.tf
env/cloud/idp/terragrunt.hcl

Revert the IdP resources for now since the IdP performance tests are complete.  As demand grows, these will likely need to be increased.
Note that the RDS max ACU has been increased from its original value as the database is bottlenecked under load at 2 ACUs.
The rationale for dropping the ECS resources below minimum recommended values (4 vCPU, 8 GB memory) is that the current IdP demand is very low and the response times are acceptable for that demand.

test: revert IdP ECS/RDS resources

---

aws/idp/ecs.tf
idp/docker/config.yaml

Update the IdP config to specify the database max connections and max idle connections.
Although these should not be needed because we use the RDS proxy to manage our connections, there is a bug report stating that leaving these empty causes slower access token responses.
The ECS task resources have also be bumped back up to the minimum recommend values to run one more performance test.
- https://github.com/zitadel/zitadel/issues/6755

fix: set database max connection properties

---

aws/idp/ecs.tf

Drop IdP ECS task resources back to 1 vCPU and 2 GB memory to see how it performs with the database config fix in place.

revert: original IdP ECS task resources

---

lambda-code/reliability/lib/dataLayer.ts
lambda-code/reliability/lib/types.ts
lambda-code/reliability/lib/utils.ts

When we previously rolled out the [formattedDate component](https://github.com/cds-snc/platform-forms-client/pull/3581) the reliability container was not updated with the ability to process/format the response type.

fix: Process formattedDate type response

---

aws/alarms/locals.tf

Add new error patterns to suppress OIDC request errors caused by issues on the user's end.
This will prevent the following errors from being posted in Slack:

chore: suppress user OIDC request errors

---

lambda-code/nagware/lib/gc-notify-client.ts
lambda-code/reliability/lib/gc-notify-client.ts

Increases the default timeout of the Notify Client from 2 seconds to 5 seconds.

fix: Increase default timeout to Notify

---

aws/idp/lb.tf
aws/load_balancer/lb.tf

Update to the latest recommend ALB SSL policy which is [FIPS 140-3](https://csrc.nist.gov/pubs/fips/140-3/final) compliant.

chore: upgrade ALB to latest recommend SSL policy

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/load_testing/inputs.tf
aws/load_testing/lambda.tf
aws/load_testing/parameters.tf
env/cloud/load_testing/terragrunt.hcl
lambda-code/load-testing/Dockerfile
lambda-code/load-testing/README.md
lambda-code/load-testing/main.py
lambda-code/load-testing/tests/behaviours/api.py
lambda-code/load-testing/tests/behaviours/idp.py
lambda-code/load-testing/tests/behaviours/submit.py
lambda-code/load-testing/tests/utils/task_set.py

Add AWS SSM parameters needed by the load tests to run.  This includes changes to the Lambda so that it can read these parameters and load them into the execution environment.
The reason these are not being passed in directly as Lambda environment variables is because these are stored as plain text and can be leaked by AWS CLI commands.

feat: add SSM parameters for the load tests

---

aws/redis/redis.tf

Localstack does not support automatic failover with only a single instance.

Fix: Certain Redis infra features need to be disabled for localstack

---

lambda-code/audit-logs/main.ts

Now that granting and revoking form access is a public feature we can stop the warning in Slack of these previously only administrative actions.

chore: Remove warn on grant and revoke form access

---

aws/load_balancer/waf.tf

Removes the blanket and POST rate limiting on the API Server URL that is co-hosted with the GCForms app in ECS and share the same Load Balancer and WAF Rules.
The API remains protected through it's own implementation of Token Bucket Rate Limiting.

fix: Remove rate limiting WAF on api domain url

---

lambda-code/reliability/lib/dataLayer.ts
lambda-code/submission/main.ts

Part 1 of https://github.com/cds-snc/platform-forms-client/issues/4287
Context: With the addition of the new StatusCreatedAt GSI for the API we will need to get the submission `CreatedAt` value on `CONF#` items in DynamoDB for the web application to be able to get it and update the new `Status#CreatedAt` field during submission confirmation.
- Adds CreatedAt field to Vault `CONF#` items

feat: add CreatedAt field to Vault CONF# items

---

aws/load_balancer/waf.tf

The previous logic was such that although an APP or API path was valid it would be blocked by the opposing service rule.  
This fixes the logic to be: `service_url && !uri` instead of `!(service_url && uri)`
app && !uri
app = true && uri = false = block
app = false && uri = true = allow
app = true && uri = true = allow
app = false && uri = false = allow  
and 
api && !uri
api = true && uri = false = block
api = false && uri = true = allow
api = true && uri = true = allow
api = false && uri = false = allow   
Have faith in my logic deduction abilities on a Friday morning running on only 2 cups of coffee.

fix: WAF rule logic

---

aws/load_balancer/waf.tf

Adds missing `api` check on APP WAF rule.
Trust me..... what could go wrong??   (cough cough)

Fix: Add missing api path check on APP WAF rule

---

aws/alarms/cloudwatch_api.tf

Updates the Cloudwatch filter on the API log stream to catch `logMessage` style error and warn entries and send them to Notify.

fix: update api cloudwatch filter to catch logMessage style json

---

aws/load_balancer/waf.tf

Part 5 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Removes POST request limit in our WAF rules. This is now replaced by https://github.com/cds-snc/forms-terraform/pull/892

chore: remove POST request limit

---

aws/network/security_groups_lambda.tf

Fixes inverted PrivateLink security group rule.
Was allowing traffic from privatelink => lambda instead of lambda => privatelink

fix: Inverted privatelink rule

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/rds/rds.tf

Update the Terraform now that that Staging Serverless v1 to v2 upgrade is complete.  This also re-enables the workflows managing Staging infrastructure.
The Production workflows will be re-enabled once the upgrade has been completed in that environment.
- https://github.com/cds-snc/platform-core-services/issues/630

fix: RDS serverless v2 Terraform sync

---

.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-plan-production.yml

Re-enable the Production Terraform workflow management of the `rds` module now that the Serverless v2 upgrade is complete.
- https://github.com/cds-snc/platform-core-services/issues/630

chore: re-enable TF management of rds module

---

aws/load_balancer/waf.tf

Modifies WAF Dynamic IP rule from Count to Block

chore: Enable dynamic ip block on WAF

---

aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_app.tf
aws/alarms/cloudwatch_idp.tf

- Updates alarms around no healthy hosts to treat missing data as breaching
Why?
When we shutdown the web application, all registered targets in the current active target group are being deleted so both the `HealthyHostCount` and `UnHealthyHostCount` metrics are not available.

fix: no healthy hosts alarms should treat missing data as breaching

---

aws/load_balancer/route53_health_checks.tf

- Adds reference names to previously created Route53 health checks to help identify what they mean when inside AWS Console

chore: add reference name to previously created Route53 health checks

---

lambda-code/nagware/lib/dynamodbDataLayer.ts

Part 7 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Replaces any reference to the old `Status` with new `Status#CreatedAt` attribute when requesting Vault items.

refactor: replace use of Status with new Status#CreatedAt attribute when requesting Vault items

---

lambda-code/reliability/lib/dataLayer.ts

This is related to the incident `email form submission stuck in DLQ / Forms`
- Fixes issue with checkbox component not able to process any response that is not of type array.
- Run the scenario that was mentioned in the Slack threads after you deployed the new Reliability Lambda update

fix: handle empty string response for checkbox components

---

aws/load_balancer/waf.tf

Adds the versioning moniker to the WAF rules for API server.
Accepts: 
- `/v1/forms/`
- `/v99/forms`
- `/forms`

chore: update waf to take `v[0-9][0-9]` for api server

---

localstack_services.sh

- Deletes `.terraform.lock.hcl` file on clean up step

chore: delete .lock.hcl file when running clean up step

---

aws/idp/waf.tf

Enable Dynamic IP Blocking rule to BLOCK instead of COUNT on IDP.  (Already blocks on app and api)

chore: IDP waf dynamic Ip now blocks

---

aws/rds/outputs.tf

Fixes output of RDS subnet id to be a string instead of a list

fix: Set output of RDS subnet id to string

---

aws/alarms/athena.tf
aws/alarms/inputs.tf
aws/glue/inputs.tf
aws/glue/jobs.tf
aws/rds/outputs.tf
env/cloud/alarms/terragrunt.hcl
env/cloud/glue/terragrunt.hcl

Use the reader-only RDS cluster endpoint for non-app use like Athena and Glue

chore:  Use RDS reader endpoint for non-app use

---

aws/ecr/ecr.tf

Should fix an issue on previous apply where quotes were not used within `jsonencode` for ECR policy.

fix: add missing quotes in ecr policy

---

aws/glue/iam.tf
aws/glue/locals.tf
aws/glue/s3.tf

Add an S3 replication rule and IAM role to replicate the processed and historical data to the Platform data lake Raw S3 bucket.
⚠️  **Note:** the plan is to test out the replication in Staging, and then once it's confirmed to be working, disable Staging replication and only replicate from the Prod account.

feat: add S3 replicate rule to Platform data lake

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/ecr/ecr.tf
aws/ecr/inputs.tf
env/cloud/ecr/terragrunt.hcl

Reverts previous PR's targeting ECR policy for across account sharing until we get this wrapped up properly.

chore: revert failing ecr policy

---

aws/glue/s3.tf

Update the S3 replication rule to only replicate date to the Platform data lake in production.
This is because the Platform data lake currently only has one environment and we do not want to intermingle Staging and Production data.

feat: replicate prod data to the Platform data lake

---

aws/glue/s3.tf

Disable the S3 replication rule to the Platform data lake until the ETL job testing is complete.
ℹ️  It is expected that there is no Terraform plan since the replication rule was already disabled in Staging.

chore: temporarily disable data replication to data lake

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/ecr/ecr.tf
aws/ecr/inputs.tf
env/cloud/ecr/terragrunt.hcl

We need to use explicit aws account ids for developers in the ECR policy as the principals making the API calls to Staging are not part of the "organization" as they are service accounts.

chore: Use explicit accounts ids as org id does not work

---

lambda-code/nagware/lib/templates.ts
lambda-code/reliability/lib/templates.ts

- Reverts localstack detection when initializing Postgres connector

fix: revert localstack detection when initializing Postgres connector

---

Makefile
local_dev_files/sso_login.sh

Adds a login guard to the following `make` commands: 
- lambda
- lambdas
- connect_env
- destroy_env
- build_env
- build_module

feature: sso login script

---

aws/lambdas/iam.tf

- Adds missing permissions for the Response Archiver lambda function to execute S3 CopyObject operations. Now that the file scanner adds tags to S3 objects we need new permissions (see https://medium.com/collaborne-engineering/s3-copyobject-access-denied-5f7a6fe0393e).

fix: missing permissions to copy S3 object with tags

---

local_dev_files/connect_vpn.sh

Updates `connect_env` script to use terraform and terragrunt versions specified in the other scripts.  It also updates the terragrunt command in the script to remove `--terragrunt` from the flag names as they are now depreciated.

fix: update connect_env to use latest tf and tg version

---

local_dev_files/build_dev_env.sh
local_dev_files/connect_vpn.sh

Some small housekeeping:
- ensure all terragrunt commands reference the new CLI pattern without the `--terragrunt` prefix.
- Add terragrunt env var to all scripts that reference package cache

chore: script clean up

---

Makefile
local_dev_files/build_dev_env.sh
local_dev_files/connect_vpn.sh
local_dev_files/destroy_dev_env.sh

add back `-auto-approve` flag as it is only passed in silently when using the new `run --all` command which is still behind an `--experimental` flag.

fix: add back auto-approve

---

aws/glue/s3.tf

Update the data S3 replication rule so that Staging data is sent to the Platform Data Lake.  This will allow us to validate the data before making Production data available.

chore: re-enable Staging data replication to Data Lake

---

aws/load_balancer/lb.tf

Linked to https://github.com/cds-snc/platform-forms-client/pull/5161
- Bumps API LB listener rule to priority 49999

feat: rainbow deployment

---

aws/lambdas/iam_forms_lambda_client.tf
aws/lambdas/outputs.tf

- Skips deployment of forms lambda IAM roles for scratch accounts

fix: skip lambda IAM role creation in scratch account

---

aws/glue/s3.tf

Update the S3 data replication to the data lake so that it is enabled for Production.  Data validation has been completed with the Staging data and all looks good.

feat: enable data lake replication from production

---

aws/oidc_roles/iam_roles.tf

Reduces the complexity and naming of oidc roles required for prisma migration.  Instead of using different names for the roles required for Staging and Production the same role name is used by the claim is based on the env.

chore: reduce the number of oidc roles created

---

aws/oidc_roles/iam_policies.tf

Adds the `GetFunction` permission to the Prisma Migration OIDC role.  The permission is needed in order to check if the lambda is active and can be invoked.

fix: add lambda get function to prisma role

---

aws/lambdas/prisma_migration.tf

Lambda running very slowly due to max memory usage.  In click-ops testing 512 seems to do the trick.

fix: Boost lambda memory

---

lambda-code/cognito-email-sender/package.json
lambda-code/cognito-email-sender/yarn.lock
lambda-code/nagware/lib/templates.ts
lambda-code/nagware/package.json
lambda-code/nagware/yarn.lock
lambda-code/reliability/lib/templates.ts
lambda-code/reliability/package.json
lambda-code/reliability/yarn.lock

- Bumps https://www.npmjs.com/package/@gcforms/connectors package from v1 to v2 (removal of Localstack support)

chore: bump connectors package from v1 to v2

---

lambda-code/cognito-email-sender/package.json
lambda-code/cognito-email-sender/yarn.lock
lambda-code/nagware/package.json
lambda-code/nagware/yarn.lock
lambda-code/reliability/package.json
lambda-code/reliability/yarn.lock

- Updates Connectors package to version `2.0.2` (to pull in Axios update `1.8.4`)

chore: update connectors package to version 2.0.2 in order to pull Axios 1.8.4 update

---

lambda-code/nagware/main.ts

- Disables Nagware notifications on Slack

chore: disable Nagware Slack notifications

---

aws/alarms/cloudwatch_app.tf
aws/load_balancer/waf.tf

- Replaces the login out of country Cognito login alarm by a simple flag using WAF header injection. The new HTTP header will be used by the web application to produce an info log

feat: replaced out of country alarm by WAF header injection for detection within the web application

---

lambda-code/nagware/lib/templates.ts

- Makes Nagware lambda use a single Postgres connector instance during its lifecycle

chore: Nagware lambda use a single Postgres connector instance

---

aws/api/ecs.tf

- Adds missing Scan permission on DynamoDB for the API service (this operation is used by the newer version of the `/status` endpoint)

fix: add missing Scan permission on DynamoDB for the API service

---

aws/alarms/cloudwatch_api.tf
aws/alarms/cloudwatch_idp.tf
aws/load_balancer/lb.tf

- Adds SEV1 suffix to API and IdP HealthyHostCount alarm
- Increases API `/status` health check polling interval from 10 to 20

feat: bump healthy host count alarm to SEV1

---

aws/app/ecs_iam.tf
aws/app/inputs.tf
env/cloud/app/terragrunt.hcl

Add read permissions to ECS task for the dynamodb tables and indexes for App and API Audit Logs.
Supports PR cds-snc/platform-forms-client#5476

chore: Allow ECS task to access Audit Logs for APP and API

---

aws/rds/rds.tf

- Fixes version mismatch between Aurora PostgreSQL in Production vs what was set in our Terraform config

fix: aurora postgresql version

---

aws/network/development_env/network.tf
env/cloud/lambdas/terragrunt.hcl

- Adds missing service discovery resource for when deploying environment to scratch accounts
- Disables IdP and API dependencies in Lambda module when in dev mode

fix: missing service discovery resource in development mode

---

aws/network/security_group_api_end_to_end_test.tf

- Adds missing connection between new API end to end test security group and private link one. This will resolve the communication problem with the AWS Lambda API (when we want to invoke the Submission lambda)

fix: API end to end test security group is missing connection with private link one

---

aws/network/security_group_api_end_to_end_test.tf

- Opens egress rule for API end to end test security group to the whole internet

fix: api end to end test security group can egress to the whole internet

---

aws/idp/ecs.tf
aws/idp/lb.tf
idp/Makefile
idp/docker/Dockerfile
idp/docker/config.yaml

- Disables TLS traffic enforcement in Zitadel's configuration. The AWS load balancer will handle TLS for us. The goal is to simplify local communication over VPC for services like Web App / API and IdP.
Note:
This may break the API end to end test but I will fix it in a subsequent PR.

chore: disable Zitadel TLS traffic enforcement

---

aws/lambdas/api_end_to_end_test.tf
lambda-code/api-end-to-end-test/src/lib/idpClient.ts

- Removes custom httpAgent that does not verify TLS certificate validity now that we have removed TLS support from Zitadel

fix: API end to end test does not need custom httpAgent to bypass TLS certificate verification

---

aws/api/ecs.tf
aws/api/inputs.tf
env/cloud/api/terragrunt.hcl

- Adds new environment variables to the API ECS task for new API build in order to enable local communication with Zitadel

feat: adds new environment variables to the API ECS task for new API build in order to enable local communication with Zitadel

---

idp/docker/config.yaml

Trying to see if changing the connection max lifetime and number of connections impacts the error being registered in staging.

Chore: Tweak to IDP database connection config

---

idp/docker/config.yaml

Update external port to be 443,
Update Notifications to use parallel instead of legacy to see if the errors are resolved.

Chore: Zitadel config

---

idp/docker/config.yaml

Try to manually set Notification settings to Legacy for Zitadel to troubleshoot if error resolves

chore: Zitadel switch to legacy for notifications

---

idp/docker/config.yaml

Enable debug logs to see if we can get better insight into what is causing the error to throw in Zitadel.

chore: Change log level to debug and enable Notifcation worker

---

idp/docker/config.yaml

Debug level logs did not produce any more info about the errors.  Switching back to "info" level and giving up until next week.

chore: change from debug to info level for Zitadel

---

.github/workflows/terragrunt-apply-production.yml

Modify github production workflow to hold back Zitadel major version update while we continue to test in Staging.

chore: Modify github release to hold back zitadel update

---

aws/load_balancer/waf.tf

Ignore 404's from the app (target responses) for now.
Exclude 403's coming from the rule that blocks IP's on the list so that the IP is removed within 24 hours and does not continue to block traffic.

fix: WAF ignore 404 from LB and Dynamic IP Rule

---

aws/lambdas/reliability.tf

- Limits concurrency for Reliability lambda invocations. Limit is set to 150. When we started seeing the `remaining connection slots are reserved for non-replication superuser connections ` issue in Staging with had a peak of 218 connections on the RDS cluster.

chore: set reliability lambda concurrency to 150

---

lambda-code/load-testing/main.py

- Returns JSON string when load testing lambda execution completes

fix: return JSON string with load testing results

---

lambda-code/audit-logs-archiver/src/main.ts
lambda-code/audit-logs/src/main.ts
lambda-code/cognito-email-sender/src/main.ts
lambda-code/form-archiver/src/lib/templates.ts
lambda-code/nagware/src/lib/emailNotification.ts
lambda-code/reliability-dlq-consumer/src/main.ts
lambda-code/reliability/src/lib/dataLayer.ts
lambda-code/reliability/src/lib/notifyProcessing.ts
lambda-code/reliability/src/lib/s3FileInput.ts
lambda-code/reliability/src/lib/templates.ts
lambda-code/response-archiver/src/main.ts

Context: we are trying to fix the root cause of the client load test session that failed yesterday due to reaching maximum opened connections with our RDS cluster. It looks like https://github.com/cds-snc/forms-terraform/pull/1041 was not enough. I could not yet confirm why but it could be related to https://www.npmjs.com/package/postgres having a default timeout that keeps the connection opened even after the Lambda execution has ended.
- Instantiates clients (connectors) outside of functions in Lambdas to avoid creating unnecessary connections when benefiting from warm start invocations
(https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html)
> After the invocation completes, the execution environment is frozen. To improve resource management and performance, …

refactor: instantiate clients outside of functions

---

.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-staging.yml
aws/load_testing/inputs.tf
aws/load_testing/lambda.tf
aws/load_testing/parameters.tf
lambda-code/load-testing/example_test_configuration.json
lambda-code/load-testing/tests/behaviours/api.py
lambda-code/load-testing/tests/behaviours/idp.py
lambda-code/load-testing/tests/behaviours/submit_client.py
lambda-code/load-testing/tests/behaviours/submit_infra.py
lambda-code/load-testing/tests/test_api.py
lambda-code/load-testing/tests/test_global_system.py
lambda-code/load-testing/tests/test_send_submissions_through_client.py
lambda-code/load-testing/tests/test_submit_through_client_with_file_upload.py
lambda-code/load-testing/tests/utils/config.py
lambda-code/load-testing/tests/utils/form_submission_decrypter.py
lambda-code/load-testing/tests/utils/http2_user.py
lambda-code/load-testing/tests/utils/jwt_generator.py

- Removes unused load testing lambda env variables
- Reworks API load test scenario to match real use case (get new responses, fetch and confirm them all)
- Tweaks load testing implementation to work with new upcoming test-setup tool https://github.com/cds-snc/platform-forms-client/pull/5893
- Distributes test forms to virtual users in an even pattern
Note: once merged we can remove `STAGING_LOAD_TESTING_FORM_ID` and `STAGING_LOAD_TESTING_FORM_PRIVATE_KEY` from our Github secrets

feat: revamp API load testing scenario

---

aws/dynamodb/dynamo.tf
aws/lambdas/iam.tf
lambda-code/file-upload-cleanup/src/lib/datalayer.ts
lambda-code/submission/src/main.ts

Fixes https://github.com/cds-snc/platform-forms-client/issues/5980
- Replaces `FileKeysCreatedAt` Global Secondary Index with `HasFileKeysByCreatedAt` to avoid using the `FileKeys` data field that can become too large ([to be a Primary Key](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Constraints.html#limits-partition-sort-keys)) when people upload a lot of files.

fix: replace old FileKeysCreatedAt with new HasFileKeysByCreatedAt to resolve issue with primary key being too large

---

lambda-code/load-testing/custom_lambda_load_test.py
lambda-code/load-testing/example_test_configuration.json
lambda-code/load-testing/main.py
lambda-code/load-testing/run_load_test_in_lambdas.py
lambda-code/load-testing/tests/behaviours/api.py
lambda-code/load-testing/tests/behaviours/idp.py
lambda-code/load-testing/tests/behaviours/submit_client.py
lambda-code/load-testing/tests/behaviours/submit_infra.py
lambda-code/load-testing/tests/utils/config.py

- Enhances load test lambda to allow test form assignation based on thread id (Invokust). The goal is to simulate one user per form using Invokust threads (1 thread = 1 lambda). This will be useful when load testing the API service

feat: enhance load test lambda to allow test form assignation based on thread id

---

.github/module-filter.yml
.github/workflows/terragrunt-apply-production.yml
.github/workflows/terragrunt-apply-staging.yml
.github/workflows/terragrunt-plan-all-staging.yml
.github/workflows/terragrunt-plan-production.yml
.github/workflows/terragrunt-plan-staging.yml
aws/idp/ecs.tf
aws/idp/inputs.tf
aws/idp/rds.tf

- Adds `pr_review` to the list of filtered modules so that we don't have to run Terraform plan on it when nothing has changed in that module
- Deletes IdP AWS RDS Proxy as it causes problems with recent versions of Zitadel (now that it includes Riverqueue as a dependency)

chore: delete IdP RDS Proxy

---

aws/idp/ecs.tf

- Adds back `ZITADEL_DATABASE_POSTGRES_USER_USERNAME` and associated password to Zitadel ECS task definition

fix: try to add back ZITADEL_DATABASE_POSTGRES_USER_USERNAME and associated PASSWORD to Zitadel ECS task definition

---

aws/s3/s3.tf

- Fixes a weird problem where deploying the `aws_s3_bucket_notification` Terraform resource breaks the AWS Guard Duty integration.
Here is the Terraform output for the last commit that was deployed to Staging:
```
18:25:45.352 STDOUT terraform: Terraform used the selected providers to generate the following execution
18:25:45.352 STDOUT terraform: plan. Resource actions are indicated with the following symbols:
18:25:45.352 STDOUT terraform:   ~ update in-place
18:25:45.352 STDOUT terraform: Terraform will perform the following actions:
18:25:45.352 STDOUT terraform:   # aws_s3_bucket_notification.file_upload will be updated in-place
18:25:45.353 STDOUT terraform:   ~ resource "aws_s3_bucket_notification" "file_upload" {
18:25:45.353 STDOUT terraform:       ~ eventbridge = true -> false …
```

fix: deployment of aws_s3_bucket_notification Terraform resource breaks Guard Duty integration

---

aws/s3/s3.tf

Add CORS configuration to S3 vault storage so a browser can initiate the connection of a signed url.

Fix: Add cors to retrieve vault files

---

lambda-code/load-testing/.gitignore
lambda-code/load-testing/Dockerfile
lambda-code/load-testing/Makefile
lambda-code/load-testing/custom_create_settings.py
lambda-code/load-testing/main.py
lambda-code/load-testing/requirements.txt
lambda-code/load-testing/tests/behaviours/api.py
lambda-code/load-testing/tests/behaviours/idp.py
lambda-code/load-testing/tests/behaviours/submit_client.py
lambda-code/load-testing/tests/behaviours/submit_infra.py
lambda-code/load-testing/tests/utils/sequential_task_set_with_failure.py

- Upgrades Locust to version 2.39.1
- Forces use of Python 3.12 in load test project
- Revises use of `HttpSession` from Locust
- Removes submission attachments download process from API test scenario

fix: load test bug related to compatibility between invokust and locust

---

aws/alarms/cloudwatch_app.tf
aws/alarms/inputs.tf
aws/sqs/outputs.tf
env/cloud/alarms/terragrunt.hcl

- Fixes DLQ alarm configuration due to misleading example 😅 (resource name was ARN but actual value pointed at name)

fix: DLQ alarms should use name of queue instead of ARN

---

aws/lambdas/audit_log.tf

- Limits to 10 the number of concurrent audit logs lambda running at a time

chore: limit to 10 the number of concurrent audit logs lambda running at a time

---

aws/lambdas/audit_log.tf

- Decreases number of concurrent audit logs lambda running at a time to 5 (instead of 10)

chore: limit to 5 the number of concurrent audit logs lambda running at a time
